function h = getScribeToolbarButtons(fig)
% Returns the scribe-related buttons from the various toolbars present in
% the figure.

%   Copyright 2006 The MathWorks, Inc.

c = findobj(allchild(fig),'flat','Type','uitoolbar');

% ToDo: Instead of hardcoding button names below, delegate
% and have this check done dynamically.
h = [uigettool(c,'Standard.EditPlot'); ...
    uigettool(c,'Exploration.ZoomIn'); ...
    uigettool(c,'Exploration.ZoomOut'); ...
    uigettool(c,'Exploration.Pan'); ...
    uigettool(c,'Exploration.Rotate'); ...
    uigettool(c,'Exploration.DataCursor'); ...
    uigettool(c,'Exploration.Brushing'); ...    
    uigettool(c,'Annotation.InsertEllipse'); ...
    uigettool(c,'Annotation.InsertRectangle'); ...
    uigettool(c,'Annotation.InsertTextbox'); ...
    uigettool(c,'Annotation.InsertTextArrow'); ...
    uigettool(c,'Annotation.InsertDoubleArrow'); ...
    uigettool(c,'Annotation.InsertArrow'); ...
    uigettool(c,'Annotation.InsertLine'); ... 
    uigettool(c,'Annotation.Pin'); ...
    uigettool(c,'Annotation.AlignDistribute')];