function appendRange(this, minExtremum, maxExtremum)
    % APPENDRANGE this function expands the range by new values for minimum
    % and maximum
    
    % Copyright 2017 The MathWorks, Inc.
    
    [this.minExtremum, this.maxExtremum] = SimulinkFixedPoint.extractMinMax([...
        this.minExtremum ...
        this.maxExtremum ...
        minExtremum ...
        maxExtremum]);
end