function  [validComponentTypes] = getValidComponentTypesfor16b17a()   
% function that returns a list of valid components types for 16b and 17a
% i.e. these are the only valid components for 16b and 17a..
% It is used in the forward compatibility case of converting an app back to
% 16b and 17a.
% Note:  This list should not change

% Copyright 2017 The MathWorks, Inc.
validComponentTypes = ... 
    {'matlab.ui.Figure' ,...
    'matlab.ui.container.ButtonGroup' ,...
    'matlab.ui.container.Panel' ,...
    'matlab.ui.container.Tab' ,...
    'matlab.ui.container.TabGroup' ,...
    'matlab.ui.control.Button' ,...
    'matlab.ui.control.CheckBox' ,...
    'matlab.ui.control.DiscreteKnob' ,...
    'matlab.ui.control.DropDown' ,...
    'matlab.ui.control.EditField' ,...
    'matlab.ui.control.Gauge',...
    'matlab.ui.control.Knob' ,...
    'matlab.ui.control.Label' ,...
    'matlab.ui.control.Lamp' ,...
    'matlab.ui.control.LinearGauge',...
    'matlab.ui.control.ListBox',...
    'matlab.ui.control.NinetyDegreeGauge',...
    'matlab.ui.control.NumericEditField',...
    'matlab.ui.control.RadioButton',...
    'matlab.ui.control.RockerSwitch' ,...
    'matlab.ui.control.SemicircularGauge',...
    'matlab.ui.control.Slider',...
    'matlab.ui.control.Spinner' ,...
    'matlab.ui.control.StateButton' ,...
    'matlab.ui.control.Switch' ,...
    'matlab.ui.control.Table' ,...
    'matlab.ui.control.TextArea',...
    'matlab.ui.control.ToggleButton',...
    'matlab.ui.control.ToggleSwitch',...
    'matlab.ui.control.UIAxes' };

end

