# Makefile for uicomponents/components_m
COMPONENT := uicomponents/components_m

include $(MAKE_INCLUDE_DIR)/pcoderules.gnu

include $(MAKE_INCLUDE_DIR)/build_component.mk

prebuild : $(PCODE_PREBUILD_TARGETS)

build: $(PCODE_BUILD_TARGETS)
