classdef AbstractObject < handle
% ABSTRACTOBJECT Class definition of abstract interfaces

% Copyright 2012-2016 The MathWorks, Inc.

    methods
        function propList = getPreferredProperties(~)
            propList =  {...
                'Name',...
                'Run',...
                'SimDT',...
                'SpecifiedDT'...
                'DesignMin', ...
                'DesignMax', ...
                'SimMin',...
                'SimMax',...
                'OverflowWrap',...
                'OverflowSaturation', ...
                'ProposedDT', ...
                'Accept',...
                'ProposedMin',...
                'ProposedMax',...
                'CompiledDesignMin',...
                'CompiledDesignMax'
                        };
        end

        function propList = getPossibleProperties(~)
            propList =  {...
                'LogSignal', ...
                'SignalName',...
                'Name',...
                'Run',...
                'SimDT',...
                'CompiledDT',...
                'SpecifiedDT'...
                'DesignMin', ...
                'DesignMax', ...
                'DerivedMin', ...
                'DerivedMax', ...
                'SimMin',...
                'SimMax',...
                'OverflowWrap',...
                'OverflowSaturation',...
                'DivideByZero',...
                'ProposedDT', ...
                'Accept',...
                'ProposedMin',...
                'ProposedMax',...
                'CompiledDesignMin',...
                'CompiledDesignMax',...
                'DTGroup', ...
                'InitialValueMin',...
                'InitialValueMax',...
                'ModelRequiredMin',...
                'ModelRequiredMax',...
                'WholeNumber', ...
                'HistogramData'
                        };
        end

    end
end


