function b = isStateflowChartObject(sfObj)
% ISSTATEFLOWCHARTOBJECT returns true if the object is a stateflow chart
% object

% Copyright 2012 MathWorks, Inc.
%  Date: $

b = isa(sfObj, 'Stateflow.Chart') || ...
    isa(sfObj, 'Stateflow.LinkChart') || ...
    isa(sfObj, 'Stateflow.EMChart') || ...
    isa(sfObj, 'Stateflow.TruthTableChart') || ...
    isa(sfObj, 'Stateflow.ReactiveTestingTableChart') || ...
    isa(sfObj, 'Stateflow.StateTransitionTableChart');
