classdef MATLABVariableDataArrayHandler < fxptds.AbstractDataArrayHandler
%MATLABVariableDataArrayHandler
    
% Copyright 2013-2015 The MathWorks, Inc.
    methods
        function this = MATLABVariableDataArrayHandler(data_array)
            if nargin==0
                return
            end
            this.DataArray = data_array;
        end % MATLABVariableDataArrayHandler
        
    end
    
    methods
        function variable_identifier = getUniqueIdentifier(~,data)
            if data.IsCppSystemObject
                variable_identifier = ...
                    fxptds.MATLABCppSystemObjectVariableIdentifier(...
                    data.MATLABFunctionIdentifier,...
                    data.MATLABExpressionIdentifiers,...
                    data.SymbolName,...
                    data.MxInfoID,...
                    data.InstanceCount,...
                    data.NumberOfInstances,...
                    data.TextLength);
            else
                variable_identifier = ...
                    fxptds.MATLABVariableIdentifier(...
                    data.MATLABFunctionIdentifier,...
                    data.MATLABExpressionIdentifiers,...
                    data.SymbolName,...
                    data.MxInfoID,...
                    data.InstanceCount,...
                    data.NumberOfInstances,...
                    data.TextLength);
            end
        end
        function variable_result = createResult(~,data)
            if data.IsCppSystemObject
                variable_result = fxptds.MATLABCppSystemObjectVariableResult(data);
            else
                variable_result = fxptds.MATLABVariableResult(data);
            end
        end
    end
    
end
