function [sharedoptim, fulloptim] = uselargeoptimstruct
% Check to see if the large options structure should be returned.

%   Copyright 2008-2016 The MathWorks, Inc.

fulloptim = license('test','Optimization_Toolbox');

sharedoptim = fulloptim || ...
              license('test','curve_fitting_toolbox') || ...
              license('test','statistics_toolbox') || ...
              license('test','simulink_control_design') || ...
              license('test','Video_and_Image_Blockset') || ...
              license('test','identification_toolbox');