function renderToolbars(this)

% COpyright 2017 The MathWorks, Inc.

% This has been moved to @PixelRegionTool/renderToolbars to place the
% buttons correctly on the toolbar. Keeping it here for reference.

% this.VideoInfoButton = uipushtool( ...
%     this.Application.Handles.mainToolbar, ...
%     'Tag', 'uimgr.uipushtool_VideoInfo', ...
%     'BusyAction', 'cancel', ...
%     'TooltipString', getString(message('Spcuilib:scopes:ToolTipVidInf')), ...
%     'ClickedCallback', @(hco,ev) show(this.VideoInfo, true), ...
%     'CData', this.Application.getIcon('info'));
