function renderMenus(this)

% Copyright 2017 The MathWorks, Inc.

this.VideoInfoMenu = uimenu( ...
    this.Application.Handles.toolsMenu, ...
    'Tag', 'uimgr.uimenu_VideoInfo', ...
    'Label', getString(message('Spcuilib:scopes:MenuVidInfo')), ...
    'Callback', @(hco,ev) show(this.VideoInfo, true));

hSource = this.Application.DataSource;
if isempty(hSource) || ~isDataLoaded(hSource) || this.isRGB(hSource)
    ena = 'off';
else
    ena = 'on';
end

this.ColormapMenu = uimenu( ...
    this.Application.Handles.toolsMenu, ...
    'Tag', 'uimgr.uimenu_Colormap', ...
    'Label', getString(message('Spcuilib:scopes:MenuColorMap')), ...
    'Enable', ena, ...
    'Callback', @(hco,ev) show(this.ColorMap, true));
