function formattedResults = getPackagedResults(analysisResults)
%getPackagedResults Package formatted CCA results into a struct object
%   getPackagedResults formats the input CodeCompatiblityAnalysis and
%   creates a struct object to be sent to the JS UI.

%   Copyright 2017 The MathWorks, Inc.
    import matlab.internal.codecompatibilityreport.getResultsTables;
    [compatErrors, syntaxErrors, compatWarnings, otherWarnings, checksPerformed, files ] = getResultsTables(analysisResults);
    formattedResults = struct('MATLABVersion', char(analysisResults.MATLABVersion),...
                              'analysisDate', char(analysisResults.Date),...
                              'compatErrors', table2struct(compatErrors),...
                              'syntaxErrors', table2struct(syntaxErrors),...
                              'compatWarnings', table2struct(compatWarnings),...
                              'otherWarnings', table2struct(otherWarnings),...
                              'checksTable', table2struct(checksPerformed),...
                              'fileList', table2struct(files),...
                              'rerunConfiguration', analysisResults.RerunConfiguration);
end
