function axesList = findDataAxes (fig)

figH = handle(fig);
axesList = figH.findobj ...
   ('-depth', 8, ...    % 8 is somewhat arbitrary
    '-regexp','Type','.*axes', ...
    '-or', '-isa', 'matlab.graphics.chart.Chart', ...
    'handlevisibility', 'on', ...
    '-not','tag','legend','-and','-not','tag','Colorbar');
% Note:  this is the same search used in addsubplot.
