function createILSubdialog(dlg)
% Create Integer Length content for Numeric Type dialog
%
% We don't actually register a dialog here; this is just a helper
% function that contributes UI controls to a parent dialog.

%   Copyright 2010-2012 The MathWorks, Inc.

hParent = dlg.ContentPanel;
bg = get(hParent,'BackgroundColor');
ppos = get(hParent,'Position');
pdx = ppos(3); % initial width of parent panel, in pixels
pixelFactor = dlg.UserData.dp.PixelFactor;

% MSB dialog
dy = 108 * pixelFactor;
hBAILPanel = uipanel('Parent',hParent, ...
    'Units','pix', ...
    'Position', [2 1 pdx-4 dy], ...
    'BorderType','none',...
    'Tag','il_subpanel',...
    'BackgroundColor',bg); %#ok<*PROP> %   

dlg.hBAILPanel = hBAILPanel;

inBorder = 2;
outBorder = 2;
xL = inBorder; % inMargin - # pix separation from border to widget
xb = outBorder; % lineWidth # pix on each side of panel taken by border line
x0 = inBorder+1;
y0 = inBorder+76;
dx = pdx-2*inBorder-4;
dy = 20 * pixelFactor;
dyt = 16 * pixelFactor; % text prompt heights

dlg.hBAILPrompt =  uicontrol( ...
    'Parent', hBAILPanel, ...
    'BackgroundColor',bg, ...
    'Units','pix', ...
    'HorizontalAlignment','left', ...
    'TooltipString','', ...
    'Position',[x0 y0 dx dyt], ...
    'String',getString(message('fixed:NumericTypeScope:ILConstraintPrompt')), ...
    'Tag','il_constraint',...
    'Style','text'); 

y0 = y0-dy-4;    
% Create MSB widgets
tip = getString(message('fixed:NumericTypeScope:ILConstraintMethodToolTip'));
ILConstraintEntries = strcat(getString(message('fixed:NumericTypeScope:ConstraintOptionsMaxOutRange')),'|',...
                             getString(message('fixed:NumericTypeScope:ConstraintOptionsLargestMag')),'|',...
                             getString(message('fixed:NumericTypeScope:ConstraintOptionsIntBits')));
dlg.hBAILMethod = uicontrol( ...
    'Parent', hBAILPanel, ...
    'BackgroundColor','w', ...
    'Units','pix', ...
    'TooltipString',tip, ...
    'Position',[x0 y0 dx dy], ...
    'Callback',@(h,e)setBAILMethod(dlg), ...
    'Style','popup', ...
    'Value',dlg.BAILMethod, ...
    'Tag','il_constraint_popup',...
    'String',ILConstraintEntries);

pdx2 = floor(pdx/2); % midpoint
dxL = pdx2-xb-xL-13;  % Left side is 13 pix shorter
xR = xL+dxL+4; % 1-pix gap to start of xR
dxR = pdx-xR-xb-2;

y0=y0-dy-8;
% ... that meets specified criterion.
tip = getString(message('fixed:NumericTypeScope:OverflowPercentMethodToolTip'));
dlg.hBAILPercent = uicontrol( ...
    'Parent', hBAILPanel, ...
    'BackgroundColor','w', ...
    'Units','pix', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','right', ...
    'Position',[x0 y0 dxL dy], ...
    'String',sprintf('%d',dlg.BAILPercent), ...
    'Callback',@(h,e)setBAILPercent(dlg,h), ...
    'Tag','il_overflow_percent_edit',...
    'Style','edit'); 

tip = getString(message('fixed:NumericTypeScope:OverflowCountMethodToolTip')); 
dlg.hBAILCount = uicontrol( ...
    'Parent', hBAILPanel, ...
    'BackgroundColor','w', ...
    'Units','pix', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','right', ...
    'Position',[x0 y0 dxL dy], ...
    'String',sprintf('%d',dlg.BAILCount), ...
    'Callback',@(h,e)setBAILCount(dlg,h), ...
    'Tag','il_overflow_count_edit',...
    'Style','edit'); 

tip = getString(message('fixed:NumericTypeScope:UnitsMethodToolTip'));
ILOverflowUnitsEntries = strcat(getString(message('fixed:NumericTypeScope:UI_PercentStr')),'|',...
                                 getString(message('fixed:NumericTypeScope:UI_CountStr')));
dlg.hBAILUnits = uicontrol( ...
    'Parent', hBAILPanel, ...
    'BackgroundColor','w', ...
    'Units','pix', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','left', ...
    'Position',[xR y0 dxR dy], ...
    'String',ILOverflowUnitsEntries, ...
    'Callback',@(h,e)setBAILUnits(dlg,h), ...
    'Value',dlg.BAILUnits, ...
    'Tag','il_overflow_units_popup',...
    'Style','popup'); 

tip = getString(message('fixed:NumericTypeScope:LargestMagToolTip'));
dlg.hBAILValuePrompt = uicontrol( ...
    'Parent', hBAILPanel, ...
    'BackgroundColor',bg, ...
    'TooltipString',tip, ...
    'HorizontalAlignment','right', ...
    'Enable','inactive', ...  % allow mouse drag on panel
    'Units','pix', ...
    'Position',[x0 y0 dxL dyt], ...
    'String',getString(message('fixed:NumericTypeScope:ILFLValuePrompt')), ...
    'Tag','il_value_prompt',...
    'Style','text'); 

dlg.hBAILSpecifyMagnitude = uicontrol( ...
    'Parent',hBAILPanel, ...
    'BackgroundColor','w', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','left', ...
    'Units','pix', ...
    'Position',[xR y0 dxR dy], ...
    'String',sprintf('%g',dlg.BAILSpecifyMagnitude), ...
    'Callback',@(h,e)setBAILMagEdit(dlg,h), ...
    'Tag','il_msb_magnitude_edit',...
    'Style','edit'); 

% Specify Bits goes on same row as Specify Magnitude
tip = getString(message('fixed:NumericTypeScope:ILBitsToolTip'));
dlg.hBAILSpecifyBits = uicontrol( ...
    'Parent',hBAILPanel, ...
    'BackgroundColor','w', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','left', ...
    'Units','pix', ...
    'Position',[xR y0 dxR dy], ...
    'String',sprintf('%g',dlg.BAILSpecifyBits), ...
    'Callback',@(h,e)setBAILSpecifyBits(dlg,h), ...
    'Tag','il_bits_edit',...
    'Style','edit'); 

y0=y0-dy-8;
% Alt: use safety factor, not guard bits
%      'Increase MSB weight beyond minimum required'
tip = getString(message('fixed:NumericTypeScope:ExtraILBitsToolTip'));
dlg.hBAILGuardBitsPrompt = uicontrol( ...
    'Parent', hBAILPanel, ...
    'BackgroundColor',bg, ...
    'TooltipString',tip, ...
    'Enable','inactive', ...
    'HorizontalAlignment','right', ...
    'Units','pix', ...
    'Position',[x0 y0 dxL dyt], ...
    'String',getString(message('fixed:NumericTypeScope:ILFLExtraILBitsPrompt')), ... % Guard bits'
    'Tag','il_guard_bits_prompt',...
    'Style','text'); 

dlg.hBAILGuardBits = uicontrol( ...
    'Parent', hBAILPanel, ...
    'BackgroundColor','w', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','left', ...
    'Units','pix', ...
    'Position',[xR y0 dxR dy], ...
    'String',sprintf('%d',dlg.BAILGuardBits), ...
    'Callback',@(h,e)setBAILGuardBits(dlg,h), ...
    'Tag','il_guard_bits_edit',...
    'Style','edit'); 
