function createILFLSubdialog(dlg)
% Create content for the combined IL & FL options.

%   Copyright 2010-2012 The MathWorks, Inc.

hParent = dlg.ContentPanel;
bg = get(hParent,'BackgroundColor');
ppos = get(hParent,'Position');
pdx = ppos(3); % initial width of parent panel, in pixels
pixelFactor = dlg.UserData.dp.PixelFactor;

% MSB dialog
dy = 108 * pixelFactor;

hBAILFLPanel = uipanel('Parent',hParent, ...
    'Units','pix', ...
    'Position', [2 1 pdx-4 dy], ...
    'BorderType','none',...
    'Tag', 'ilfl_subpanel',...
    'BackgroundColor',bg); %#ok<*PROP>
dlg.hBAILFLPanel = hBAILFLPanel;

inBorder = 2;
outBorder = 2;
xL = inBorder; % inMargin - # pix separation from border to widget
xb = outBorder; % lineWidth # pix on each side of panel taken by border line
x0 = inBorder+1;
y0 = inBorder+76;
dx = pdx-2*inBorder-4;
dy = 20 * pixelFactor;
dyt = 16 * pixelFactor; % text prompt heights

pdx2 = floor(pdx/2); % midpoint
dxL = pdx2-xb-xL-13;  %% Left side is 11 pix shorter. We start from 1 pixel inside the border. 
xR = xL+dxL+4; % 1-pix gap to start of xR
dxR = pdx-xR-xb-2;

tip = getString(message('fixed:NumericTypeScope:JointConstraintMethodToolTip'));
dlg.hBASpecifyPrompt = uicontrol( ...
    'Parent', hBAILFLPanel, ...
    'BackgroundColor',bg, ...
    'Units','pix', ...
    'HorizontalAlignment','left', ...
    'Enable','inactive', ...  % allow mouse drag on panel
    'Position',[x0 y0 pdx2-1 dyt], ... % estimates
    'String',getString(message('fixed:NumericTypeScope:ILFLSpecifyConstraintPrompt')), ...
    'Tag','specify_constraint_prompt',...
    'Style','text'); 

ILFLConstraintEntries = strcat(getString(message('fixed:NumericTypeScope:ConstraintOptionsMaxOutRange')),'|',...
                               getString(message('fixed:NumericTypeScope:ConstraintOptionsLargestMag')),'|',...
                               getString(message('fixed:NumericTypeScope:ConstraintOptionsIntBits')),'|',...
                               getString(message('fixed:NumericTypeScope:ConstraintOptionsSmallestMag')),'|',...
                               getString(message('fixed:NumericTypeScope:ConstraintOptionsFracBits')));
y0 = y0-dy-4; 
dlg.hBAILFLMethod =  uicontrol( ...
    'Parent', hBAILFLPanel, ...
    'BackgroundColor','w', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','right', ...
    'Units','pix', ...
    'Position',[x0 y0 dx dy], ...
    'Value',dlg.BAILFLMethod, ...
    'Callback',@(h,e)setBAILFLMethod(dlg), ...
    'String',ILFLConstraintEntries, ...
    'Tag','ilfl_constraint_popup',...
    'Style','popup'); 

% Create the widgets for each of the optimization options.
y0 = y0-dy-8;
tip = getString(message('fixed:NumericTypeScope:OverflowPercentMethodToolTip'));
dlg.hBAILFLPercent = uicontrol( ...
    'Parent', hBAILFLPanel, ...
    'BackgroundColor','w', ...
    'Units','pix', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','right', ...
    'Position',[x0 y0 dxL dy], ...
    'String',sprintf('%d',dlg.BAILPercent), ...
    'Callback',@(h,e)setBAILPercent(dlg,h), ...
    'Tag','ilfl_overflow_percent_edit',...
    'Style','edit'); 

tip = getString(message('fixed:NumericTypeScope:OverflowCountMethodToolTip'));
dlg.hBAILFLCount = uicontrol( ...
    'Parent', hBAILFLPanel, ...
    'BackgroundColor','w', ...
    'Units','pix', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','right', ...
    'Position',[x0 y0 dxL dy], ...
    'String',sprintf('%d',dlg.BAILCount), ...
    'Callback',@(h,e)setBAILCount(dlg,h), ...
    'Tag','ilfl_overflow_count_edit',...
    'Style','edit'); 

tip = getString(message('fixed:NumericTypeScope:UnitsMethodToolTip'));
ILFLOverflowUnitsEntries = strcat(getString(message('fixed:NumericTypeScope:UI_PercentStr')),'|',...
                                 getString(message('fixed:NumericTypeScope:UI_CountStr')));
dlg.hBAILFLUnits = uicontrol( ...
    'Parent', hBAILFLPanel, ...
    'BackgroundColor','w', ...
    'Units','pix', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','left', ...
    'Position',[xR y0 dxR dy], ...
    'String',ILFLOverflowUnitsEntries, ...
    'Callback',@(h,e)setBAILUnits(dlg,h), ...
    'Value',dlg.BAILUnits, ...
    'Tag','ilfl_overflow_units_popup',...
    'Style','popup'); 

tip = getString(message('fixed:NumericTypeScope:LargestMagToolTip'));
dlg.hBAILFLValuePrompt = uicontrol( ...
    'Parent', hBAILFLPanel, ...
    'BackgroundColor',bg, ...
    'TooltipString',tip, ...
    'HorizontalAlignment','right', ...
    'Enable','inactive', ...  % allow mouse drag on panel
    'Units','pix', ...
    'Position',[x0 y0-3 dxL dy], ...
    'String',getString(message('fixed:NumericTypeScope:ILFLValuePrompt')), ...
    'Tag','ilfl_value_prompt',...
    'Style','text'); 

dlg.hBAILFLSpecifyMSBMagnitude = uicontrol( ...
    'Parent',hBAILFLPanel, ...
    'BackgroundColor','w', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','left', ...
    'Units','pix', ...
    'Position',[xR y0 dxR dy], ...
    'String',sprintf('%g',dlg.BAILSpecifyMagnitude), ...
    'Callback',@(h,e)setBAILMagEdit(dlg,h), ...
    'Tag','ilfl_msb_magnitude_edit',...
    'Style','edit'); 

% Specify Bits goes on same row as Specify Magnitude
tip = getString(message('fixed:NumericTypeScope:ILBitsToolTip'));
dlg.hBAILFLSpecifyILBits = uicontrol( ...
    'Parent',hBAILFLPanel, ...
    'BackgroundColor','w', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','left', ...
    'Units','pix', ...
    'Position',[xR y0 dxR dy], ...
    'String',sprintf('%g',dlg.BAILSpecifyBits), ...
    'Callback',@(h,e)setBAILSpecifyBits(dlg,h), ...
    'Tag','ilfl_ilbits_edit',...
    'Style','edit'); 

tip = getString(message('fixed:NumericTypeScope:SmallestMagToolTip'));
dlg.hBAILFLSpecifyLSBMagnitude = uicontrol( ...
    'Parent',hBAILFLPanel, ...
    'BackgroundColor','w', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','left', ...
    'Units','pix', ...
    'Position',[xR y0 dxR dy], ...
    'String',sprintf('%g',dlg.BAFLSpecifyMagnitude), ...
    'Callback',@(h,e)setBAFLMagEdit(dlg,h), ...
    'Tag','ilfl_lsb_magnitude_edit',...
    'Style','edit'); 

tip = getString(message('fixed:NumericTypeScope:FLBitsToolTip'));
dlg.hBAILFLSpecifyFLBits = uicontrol( ...
    'Parent',hBAILFLPanel, ...
    'BackgroundColor','w', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','left', ...
    'Units','pix', ...
    'Position',[xR y0 dxR dy], ...
    'String',sprintf('%g',dlg.BAFLSpecifyBits), ...
    'Callback',@(h,e)setBAFLSpecifyBits(dlg,h), ...
    'Tag','ilfl_flbits_edit',...
    'Style','edit'); 

y0=y0-dy-8;
% Alt: use safety factor, not guard bits
%      'Increase MSB weight beyond minimum required'
tip = getString(message('fixed:NumericTypeScope:ExtraILBitsToolTip'));
dlg.hBAILFLGuardBitsPrompt = uicontrol( ...
    'Parent', hBAILFLPanel, ...
    'BackgroundColor',bg, ...
    'TooltipString',tip, ...
    'Enable','inactive', ...
    'HorizontalAlignment','right', ...
    'Units','pix', ...
    'Position',[x0 y0 dxL dyt], ...
    'String',getString(message('fixed:NumericTypeScope:ILFLExtraILBitsPrompt')), ...  %Guard Bits
    'Tag','ilfl_guard_bits_prompt',...
    'Style','text'); 

dlg.hBAILFLGuardBits = uicontrol( ...
    'Parent', hBAILFLPanel, ...
    'BackgroundColor','w', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','left', ...
    'Units','pix', ...
    'Position',[xR y0 dxR dy], ...
    'String',sprintf('%d',dlg.BAILGuardBits), ...
    'Callback',@(h,e)setBAILGuardBits(dlg,h), ...
    'Tag','ilfl_guard_bits_edit',...
    'Style','edit'); 

tip = getString(message('fixed:NumericTypeScope:ExtraFLBitsToolTip'));
dlg.hBAILFLExtraBitsPrompt = uicontrol( ...
    'Parent',hBAILFLPanel, ...
    'BackgroundColor',bg, ...
    'TooltipString',tip, ...
    'HorizontalAlignment','right', ...
    'Enable','inactive', ...
    'Units','pix', ...
    'Position',[x0 y0 dxL dyt], ...
    'String',getString(message('fixed:NumericTypeScope:ILFLExtraFLBitsPrompt')), ...
    'Tag','ilfl_extra_bits_prompt',...
    'Style','text'); 

dlg.hBAILFLExtraBits = uicontrol( ...
    'Parent',hBAILFLPanel, ...
    'BackgroundColor','w', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','left', ...
    'Units','pix', ...
    'Position',[xR y0 dxR dy], ...
    'String',sprintf('%d',dlg.BAFLExtraBits), ...
    'Callback',@(h,e)setBAFLExtraBits(dlg,h), ...
    'Tag','ilfl_extra_bits_edit',...
    'Style','edit'); 
