function createContent(dlg)
% Widgets within dialog are created in this method
%
% All widgets should be parented to hParent, or to a
% child of hParent.

%   Copyright 2010-2012 The MathWorks, Inc.

hParent = dlg.ContentPanel;
set(hParent,'Tag','bitallocation_dialog_panel');
bg = get(hParent,'BackgroundColor');
ppos = get(hParent,'Position');
pdx = ppos(3); % initial width of parent panel, in pixels

inBorder = 2;
outBorder = 2;
xL = inBorder; % # pix separation from border to widget
xb = outBorder; % # pix on each side of panel taken by border line
pdx2 = floor(pdx/2); % midpoint
dxL = pdx2-10-xb-xL;  % Left side is 10 pix shorter
xR = xL+dxL+1; % 1-pix gap to start of xR
dxR = pdx-xR-xb-xL;
pixelFactor = dlg.UserData.dp.PixelFactor;

y0 = 342 * pixelFactor;

x0=2;
dy=20 * pixelFactor;
dyt = 16 * pixelFactor;
y0=y0-dy-8;

% Signedness option
tip = getString(message('fixed:NumericTypeScope:SignedToolTip'));
dlg.hBASignedPrompt = uicontrol( ...
    'Parent', hParent, ...
    'BackgroundColor',bg, ...
    'Units','pix', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','right', ...
    'Enable','inactive', ...  % allow mouse drag on panel
    'Position',[x0 y0 dxL dyt], ... % estimates
    'String',getString(message('fixed:NumericTypeScope:SignednessPrompt')), ...
    'Style','text',...
    'Tag','signedness_prompt'); 

signedEntries = strcat(getString(message('fixed:NumericTypeScope:SignednessOptionsAuto')),'|',...
                       getString(message('fixed:NumericTypeScope:SignednessOptionsSigned')),'|',...
                       getString(message('fixed:NumericTypeScope:SignednessOptionsUnsigned')));
dlg.hBASigned = uicontrol( ...
    'Parent', hParent, ...
    'BackgroundColor','w', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','left', ...
    'Units','pix', ...
    'Position',[xR y0 dxR dy], ...
    'Value',dlg.BASigned, ...
    'Callback',@(h,e)setSignedMode(dlg), ...
    'String',signedEntries, ...
    'Style','popup',...
    'Tag','signedness_popup'); 

y0 = y0-dy-8;
tip = getString(message('fixed:NumericTypeScope:WordLengthToolTip'));
dlg.hBAWLPrompt = uicontrol( ...
    'Parent', hParent, ...
    'BackgroundColor',bg, ...
    'Units','pix', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','right', ...
    'Enable','inactive', ...  % allow mouse drag on panel
    'Position',[x0 y0 dxL dyt], ... % estimates
    'String',getString(message('fixed:NumericTypeScope:WordLengthPrompt')), ...
    'Style','text',...
    'Tag','wordlength_prompt'); 

WLEntries = strcat(getString(message('fixed:NumericTypeScope:WordLengthOptionsAuto')),'|',...
                   getString(message('fixed:NumericTypeScope:WordLengthOptionsSpecify')));
dlg.hBAWLMethod = uicontrol( ...
    'Parent', hParent, ...
    'BackgroundColor','w', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','left', ...
    'Units','pix', ...
    'Position',[xR y0 dxR dy], ...
    'Value',dlg.BAWLMethod, ...
    'Callback',@(h,e)setBAWLMethod(dlg), ...
    'String',WLEntries,...
    'Style','popup',...
    'Tag','wordlength_popup'); 

y0 = y0-dy-8;
tip = getString(message('fixed:NumericTypeScope:WordLengthBitsToolTip'));
dlg.hBAWLValuePrompt = uicontrol( ...
    'Parent', hParent, ...
    'BackgroundColor',bg, ...
    'TooltipString',tip, ...
    'HorizontalAlignment','right', ...
    'Enable','inactive', ...  % allow mouse drag on panel
    'Units','pix', ...
    'Position',[x0 y0 dxL dyt], ...
    'String',getString(message('fixed:NumericTypeScope:WLValuePrompt')), ...
    'Style','text',...
    'Tag','value_prompt');%   'FontSize',8,...
dlg.hBAWLBits = uicontrol( ...
    'Parent', hParent, ...
    'BackgroundColor','w', ...
    'TooltipString',tip, ...
    'HorizontalAlignment','left', ...
    'Units','pix', ...
    'Position',[xR y0 dxR dy], ...
    'Callback',@(h,e)setBAWLBits(dlg), ...
    'String',sprintf('%d',dlg.BAWLBits), ...
    'Style','edit',...
    'Tag','wordlength_bits_edit');  

y0 = y0-dy-8;
tip = getString(message('fixed:NumericTypeScope:GraphicalToolTip'));
dlg.hBAGraphicalMode = uicontrol(...
    'Parent', hParent, ...
    'BackgroundColor',bg, ...
    'HorizontalAlignment','left', ...
    'TooltipString',tip, ...
    'Units','pix', ...
    'Position',[x0 y0 pdx-6 dy], ...
    'String',getString(message('fixed:NumericTypeScope:GraphicalControlPrompt')), ...
    'Value',0, ...
    'Callback',@(h,e)setBAGraphicalMode(dlg),...
    'Style','checkbox',...
    'Tag','graphicalcontrol_checkbox'); 
%Shift the y coordinates slightly to avoid clipping problem
y0 = y0-(98*pixelFactor)-8;

createILFLSubdialog(dlg);
pos = get(dlg.hBAILFLPanel,'Position');
pos(2) = y0;
set(dlg.hBAILFLPanel,'Position',pos);

% Create Integer Length sub dialog
createILSubdialog(dlg);
pos = get(dlg.hBAILPanel,'Position');
pos(2) = y0;
set(dlg.hBAILPanel,'Position',pos);

% Create Fraction Length sub dialog
y0 = y0-(98*pixelFactor)-8;
createFLSubdialog(dlg);
pos = get(dlg.hBAFLPanel,'Position');
pos(2) = y0;
set(dlg.hBAFLPanel,'Position',pos);

% Set height of panel
pdy = 342 * pixelFactor;
set(hParent,'Position',[1 1 pdx pdy]);
