% This function parses the user input and invoked the AppBuilder
% constructor
% Usage: packageapp(appname, entrypointfile, depfileslist, productname, productver, productid, ...
%                             platforms, appversion, summary, description, authorname, ... 
%                     authorcontact, authorcompany, appicon, appScaledIcons, appscreenshot)
% 
%   Copyright 2012 The MathWorks, Inc.
%
function packageapp(appname, entrypointfile, depfileslist, productname, productver, productid, ...
                            platforms, appversion, summary, description, authorname, ... 
                    authorcontact, authorcompany, appicon, appscreenshot, appScaledIcons, testGuid)
                
    product.name = productname;
    product.ver = productver;
    product.id = productid;
       
    app = appcreate.internal.appbuilder(appname, entrypointfile, depfileslist, ...
                            product, platforms, appversion, summary, description, ...
                            authorname, authorcontact, authorcompany, appicon, appscreenshot, ...
                            appScaledIcons, testGuid);
    build(app);
end
