function props = getProperties(this, ~) %#ok<INUSD>
%GETPROPERTIES Get the list of properties available in the View Manager.

%   Copyright 2010-2017 The MathWorks, Inc.


props = {...
    'LogSignal', ...
    'SignalName',...
    'Run',...
    'SimDT',...
    'CompiledDT',...
    'SpecifiedDT'...
    'ProposedDT', ...
    'Accept',...
    'DesignMin', ...
    'DerivedMin', ...
    'SimMin',...
    'ProposedMin',...
    'DesignMax', ...
    'DerivedMax', ...
    'SimMax',...
    'ProposedMax',...
    'OverflowWrap',...
    'OverflowSaturation',...
    'DivideByZero',...
    'DTGroup', ...
    'InitialValueMin',...
    'InitialValueMax',...
    'ModelRequiredMin',...
    'ModelRequiredMax'...
        };
props(end+1) = {'WholeNumber'};


% [EOF]
