function allPropNames = getplotbrowserproptable

% allPropNames:  This table maps various HG object types to the properties
% that the plotbrowser is interested in.  We'll use this table to set up
% property post-set listeners as the HG objects are created.

%   Copyright 2007-2017 The MathWorks, Inc.

allPropNames = ...
    {{'matlab.graphics.axis.Axes', ...
    {'Visible', 'HandleVisibility', 'Title'}}, ...
    {'tsguis.uitspanel', ...
    {'Visible', 'HandleVisibility', 'Name'}}, ...
    {'matlab.ui.container.Panel', ...
    {'Visible', 'HandleVisibility', 'Title'}}, ...
    {'matlab.graphics.chart.primitive.Line', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'Color', 'LineWidth', 'LineStyle',  ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}}, ...
    {'matlab.graphics.chart.primitive.tall.Line', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'Color', 'LineWidth', 'LineStyle',  ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}}, ...
    {'matlab.graphics.chart.primitive.Stem', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'Color', 'LineWidth', 'LineStyle',  ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}}, ...
    {'matlab.graphics.chart.primitive.Stair', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'Color', 'LineWidth', 'LineStyle',  ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}}, ...
    {'matlab.graphics.chart.primitive.Bar', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'FaceColor', 'EdgeColor'}}, ...
    {'matlab.graphics.chart.primitive.Histogram', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'FaceColor', 'EdgeColor'}}, ...
    {'matlab.graphics.chart.primitive.Histogram2', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'FaceColor', 'EdgeColor'}}, ...
    {'matlab.graphics.chart.primitive.categorical.Histogram', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'FaceColor', 'EdgeColor'}}, ...
    {'matlab.graphics.chart.primitive.Area', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'FaceColor', 'EdgeColor'}}, ...
    {'matlab.graphics.chart.primitive.ErrorBar', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'Color', 'LineWidth', 'LineStyle'}}, ...
    {'matlab.graphics.chart.primitive.Scatter', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}}, ...
    {'matlab.graphics.chart.primitive.tall.Scatter', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}}, ...
    {'matlab.graphics.chart.primitive.Contour', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'LineColor', 'Fill'}}, ...
    {'matlab.graphics.chart.primitive.Quiver', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'Color', 'LineWidth', 'LineStyle', 'ShowArrowHead'}}, ...
    {'matlab.graphics.chart.primitive.Surface', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'FaceColor', 'EdgeColor'}}, ...
    {'matlab.graphics.primitive.Line', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'Color', 'LineWidth', 'LineStyle',  ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}}, ...
    {'matlab.graphics.primitive.Patch', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'FaceColor', 'EdgeColor'}}, ...
    {'matlab.graphics.primitive.Surface', ...
    {'Visible', 'DisplayName','HandleVisibility', ...
    'FaceColor', 'EdgeColor'}}, ...
    {'matlab.graphics.primitive.Image', ...
    {'Visible', 'HandleVisibility'}}, ...
    {'matlab.graphics.chart.primitive.FunctionLine', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'Color', 'LineWidth', 'LineStyle',  ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}}, ...
    {'matlab.graphics.chart.primitive.ConstantLine', ...
    {'Visible', 'HandleVisibility', 'Tag', ...
    'Color', 'LineWidth', 'LineStyle',  ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}}, ...
    {'matlab.graphics.function.ParameterizedFunctionLine', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'XFunction', 'YFunction', 'TRange', ...
    'Color', 'LineWidth', 'LineStyle', ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}}, ...
    {'matlab.graphics.function.FunctionLine', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'Function', 'XRange', ...
    'Color', 'LineWidth', 'LineStyle', ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}}, ...
    {'matlab.graphics.function.ImplicitFunctionLine', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'Function', 'XRange', 'YRange', ...
    'Color', 'LineWidth', 'LineStyle', ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}}, ...
    {'matlab.graphics.function.FunctionSurface', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'Function', 'XRange', 'YRange', 'ShowContours', ...
    'FaceColor', ...,
    'EdgeColor', 'LineWidth', 'LineStyle', ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}}, ...
    {'matlab.graphics.function.ImplicitFunctionSurface', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'Function', 'XRange', 'YRange', 'ZRange', ...
    'FaceColor', ...,
    'EdgeColor', 'LineWidth', 'LineStyle', ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}}, ...
    {'matlab.graphics.function.ParameterizedFunctionSurface', ...
    {'Visible', 'HandleVisibility', 'DisplayName', ...
    'XFunction', 'YFunction', 'ZFunction', ...
    'URange', 'VRange', 'ShowContours', ...
    'FaceColor', ...,
    'EdgeColor', 'LineWidth', 'LineStyle', ...
    'Marker', 'MarkerEdgeColor', 'MarkerFaceColor'}},...
    {'matlab.graphics.chart.primitive.GraphPlot',...
    {'LineWidth', 'LineStyle','Marker','MarkerSize',...
    'DisplayName','Visible', 'HandleVisibility','NodeColor',...
    'EdgeColor'}},...
    {'matlab.graphics.primitive.Polygon',...
    {'LineWidth', 'LineStyle','FaceColor','EdgeColor',...
    'DisplayName','Visible', 'HandleVisibility',...
    'EdgeColor'}}};
