function varargout = quantize(u, varargin)
%QUANTIZE Quantize except numbers within eps of 1 for UNITQUANTIZE object
%   QUANTIZE(Q,...) when Q is a UNITQUANTIZER object works the same as
%   QUANTIZE except that numbers within eps(q) of one are made exactly equal
%   to 1. 
%
%   See also QUANTIZER, QUANTIZER/QUANTIZE, QUANTIZER/UNITQUANTIZE

%   Thomas A. Bryan
%   Copyright 1999-2010 The MathWorks, Inc.

% Convert to a regular quantizer object first.
q = quantizer;
set(q,'mode',        u.mode, ...
      'roundmode',   u.roundmode,...
      'overflowmode',u.overflowmode,...
      'format',      u.format,...
      'max',         u.max,...
      'min',         u.min,...
      'noverflows',  u.noverflows,...
      'nunderflows', u.nunderflows,...
      'noperations', u.noperations);

[varargout{1:max(nargout,1)}] = unitquantize(q,varargin{:});

% Set the states of the unitquantizer from the quantizer
set(u,'max',         q.max,...
      'min',         q.min,...
      'noverflows',  q.noverflows,...
      'nunderflows', q.nunderflows,...
      'noperations', q.noperations);



