classdef LinearOrientation < internal.matlab.variableeditor.datatype.StringEnumerationWithIcon	
  properties(Constant)													
		IconPaths = { ...
			fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'Orientation_Horizontal.png'), ...
			fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'Orientation_Vertical.png') ...			
			};
		
		EnumeratedValues = {...
			'horizontal', ...			
			'vertical', ...			
			}			
	end	
end