classdef NinetyDegreeOrientation  < internal.matlab.variableeditor.datatype.StringEnumerationWithIcon	
    properties(Constant)													
		IconPaths = { ...
			fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'Orientation_NorthWest.png'), ...
			fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'Orientation_NorthEast.png'), ...
			fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'Orientation_SouthWest.png'), ...
			fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'Orientation_SouthEast.png'), ...			
			};
		
		EnumeratedValues = {...
			'northwest', ...
			'northeast', ...
			'southwest', ...
			'southeast' ...			
			}			
	end		
	
end