classdef ScaleDirection < internal.matlab.variableeditor.datatype.StringEnumerationWithIcon	
	% Data Type for 'ScaleDirection' of Gauges	
	
	properties(Constant)													
		IconPaths = { ...
			fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'ScaleDirection_Clockwise.png'), ...
			fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'ScaleDirection_Counterclockwise.png'), ...
			};
		
		EnumeratedValues = {...
			'clockwise', ...
			'counterclockwise' ...
			}			
	end	
end