classdef SemicircularOrientation < internal.matlab.variableeditor.datatype.StringEnumerationWithIcon	
   properties(Constant)													
	   IconPaths = { ...
		   fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'Orientation_North.png'), ...
		   fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'Orientation_South.png'), ...
		   fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'Orientation_West.png'), ...
		   fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'Orientation_East.png') ...
		   };
		
		EnumeratedValues = {...
			'north', ...
			'south', ...
			'west', ...			
			'east' ...			
			}			
	end		
end