classdef TitlePosition < internal.matlab.variableeditor.datatype.StringEnumerationWithIcon	
    
	properties(Constant)													
		IconPaths = { ...
			fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'TextAlignment_Horz_Left.png'), ...
			fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'TextAlignment_Horz_Center.png'), ...
			fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'TextAlignment_Horz_Right.png') ...			
			};
		
		EnumeratedValues = {...
			'lefttop', ...			
			'centertop' ...
			'righttop' ...
			}			
	end	
end
  
        
        