classdef VerticalAlignment < internal.matlab.variableeditor.datatype.StringEnumerationWithIcon	
   properties(Constant)													
		IconPaths = { ...
			fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'TextAlignment_Vert_Top.png'), ...
			fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'TextAlignment_Vert_Center.png'), ...
			fullfile(matlabroot, 'toolbox', 'matlab', 'uicomponents', 'uicomponents', 'plugin', 'appdesigner', '+inspector', '+internal', '+datatype', 'images', 'TextAlignment_Vert_Bottom.png') ...
			
			};
		
		EnumeratedValues = {...
			'top', ...
			'center' ...
			'bottom' ...
			}			
	end	
end