function tableData = init_db_table_data
% Initialize a containers.Map describing the database tables.

    tableData = containers.Map;
    
    % Names of the languages that may be associated with a file. Files may
    % have at most one language. Provides some information about the type
    % of data stored in the file.
    tableData('Language') = {...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT', ...
        'Name TEXT UNIQUE' };

    % Types of symbols (built-in, MEX-file, MATLAB function, etc.)
    % recognized by the dependency analysis algorithms.
    % The Value of each symbol type in the Symbol_Type table is
    % identical to the numeric value of the enumeration class
    % matlab.depfun.internal.MatlabType.    
    tableData('Symbol_Type') = { ...
        'Name TEXT UNIQUE' ...
        'Value INTEGER UNIQUE' };
            
    % Types of proxys
    tableData('Proxy_Type') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Type INTEGER UNIQUE' ...
        'FOREIGN KEY(Type) REFERENCES Symbol_Type(Value)' };
  
    % Type of environment to which an application may be deployed.
    % Exclusion and inclusion lists vary by target. GUIs that run in the
    % MATLAB target are prohibited in the MCR target, for example.
    tableData('Target') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Name TEXT UNIQUE' };
    
    % A named container for files.
    tableData('Component') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Name TEXT UNIQUE' ...
        'Location TEXT' };
    
    % Map between files and components.        
    tableData('Component_Membership') = {
        'File INTEGER UNIQUE NOT NULL' ...
        'Component INTEGER NOT NULL' ...        
        'FOREIGN KEY(File) REFERENCES File(ID) ON DELETE CASCADE' ...
        'FOREIGN KEY(Component) REFERENCES Component(ID)' };
    
    % Names of valid licenses
    tableData('License') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Name TEXT'};
    
    % License -> component mapping -- one entry for each license that
    % allows access to a given component.
    tableData('Component_License') = { ...
        'Component INTEGER'...
        'License INTEGER', ...
        'FOREIGN KEY(Component) REFERENCES Component(ID)', ...
        'FOREIGN KEY(License) REFERENCES License(ID)'};
    
    % File system locations -- ordered lists of Path_Items form
    % component paths.
    tableData('Path_Item') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT', ...
        'Location TEXT'};
    
    % Constructive defintion of a component's path -- operation '+'
    % adds a path item to the component's path, operation '-' removes
    % one.
    tableData('Component_Path_Item') = { ...
        'Component INTEGER', ...
        'Item INTEGER' ...
        'Target INTEGER', ...
        'Operation CHARACTER(1)' ...
        'FOREIGN KEY(Component) REFERENCES Component(ID)', ...
        'FOREIGN KEY(Item) REFERENCES Path_Item(ID)', ...
        'FOREIGN KEY(Target) REFERENCES Target(ID)' };

    % A file on the disk. 
    tableData('File') = {...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Path TEXT UNIQUE' ...
        'Language INTEGER' ...
        'Type INTEGER' ...
        'Symbol TEXT' ...
        'FOREIGN KEY(Language) REFERENCES Language(ID)' ...
        'FOREIGN KEY(Type) REFERENCES Symbol_Type(Value)' };
    
    % Proxy-Principals table
    % Proxy: class constructor/fake class constructor
    % Principals: class methods, class schema, ...
    %             package functions, package schema, etc.
    tableData('Proxy_Principal') = { ...
        'Proxy INTEGER', ...
        'Principal INTEGER', ...
        'FOREIGN KEY(Proxy) REFERENCES File(ID) ON DELETE CASCADE' ...
        'FOREIGN KEY(Principal) REFERENCES File(ID) ON DELETE CASCADE' };
    
    % The immediate dependencies of each file. A list, for example,
    % of all the functions mentioned by name in the text of the client file.
    tableData('Level0_Use_Graph') = { ...
        'Client INTEGER' ...
        'Dependency INTEGER' ...
        'FOREIGN KEY(Client) REFERENCES File(ID) ON DELETE CASCADE' ...
        'FOREIGN KEY(Dependency) REFERENCES File(ID) ON DELETE CASCADE' };
    
    % All the dependencies of each file. This table flattens the tree
    % represented by the Level0_Use_Graph. Some clients may have hundreds
    % or thousands of dependencies. This is usually the biggest table in
    % any given database.
    tableData('Proxy_Closure') = { ...
        'Client INTEGER' ...
        'Dependency INTEGER' ...
        'FOREIGN KEY(Client) REFERENCES File(ID) ON DELETE CASCADE' ...
        'FOREIGN KEY(Dependency) REFERENCES File(ID) ON DELETE CASCADE' };
    
    % Paths of file that cannot be deployed, for one reason or another.
    % Kept separate from the File table for ease of management. (And this
    % way, we know that Exclude_Files never ship.)
    tableData('Exclude_File') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Path TEXT UNIQUE' };
    
    % Per-component, per-target exclusion list.
    tableData('Exclusion_List') = { ...
        'Target INTEGER' ...
        'File INTEGER' ...
        'FOREIGN KEY(Target) REFERENCES Target(ID)' ...
        'FOREIGN KEY(File) REFERENCES Exclude_File(ID)' };
    
    % files specified in the [INCLUDE] section in the IXF file
    tableData('Include_File') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Path TEXT UNIQUE' };
    
    % Per-component, per-target exclusion list.
    tableData('Inclusion_List') = { ...
        'Component INTEGER' ...
        'Target INTEGER' ...
        'File INTEGER' ...
        'FOREIGN KEY(Component) REFERENCES Component(ID)' ...
        'FOREIGN KEY(Target) REFERENCES Target(ID)' ...
        'FOREIGN KEY(File) REFERENCES Include_File(ID)' };

    %
    % Per-toolbox builtin module information
    %
    tableData('Toolbox_Builtin_Module') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Name TEXT' };

    tableData('Component_Builtin_Module') = { ...
        'Component INTEGER' ...
        'Module INTEGER' ...
        'FOREIGN KEY(Component) REFERENCES Component(ID)' ...
        'FOREIGN KEY(Module) REFERENCES Builtin_Module(ID)' };
    
    %
    % Shared license tables
    %
    %
    % Under a shared license, client files may call shared files, even if
    % there is no license available for the shared files. The client files
    % require their own license, of course.

    % Stores the identifier of and path to the authorized client directory,
    % a directory containing functions which may call shared functions even if
    % there is no license for the feature bound to the compnent that "owns" 
    % the shared functions.
    tableData('Shared_License_Client') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Name TEXT UNIQUE', ...
        'Path TEXT', ...
        'Component INTEGER', ...
        'FOREIGN KEY(Component) REFERENCES Component(ID)' ...
        };

    % Each row grants identifies a file in the given shared license client.
    tableData('Authorized_Client_Functions') = { ...
        'File INTEGER', ...
        'Client INTEGER', ...
        'FOREIGN KEY(File) REFERENCES File(ID)', ...
        'FOREIGN KEY(Client) REFERENCES Shared_License_Client(ID)' ...
        };

    % Each row grants permission for File to be called by any functions
    % in the Authorized_Client_Functions table that have the given
    % Shared_License_Client ID.
    tableData('Shared_Functions') = { ...
        'File INTEGER', ...
        'Client INTEGER', ...
        'Provider INTEGER', ...
        'FOREIGN KEY(File) REFERENCES File(ID) ON DELETE CASCADE', ...
        'FOREIGN KEY(Client) REFERENCES Shared_License_Client(ID)', ...
        'FOREIGN KEY(Provider) REFERENCES Shared_License_Provider(ID)' ...
        };

    tableData('Shared_License_Provider') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Feature INTEGER', ...
        'Path Text', ...
        'Component INTEGER', ...
        'FOREIGN KEY(Feature) REFERENCES License(ID)', ...
        'FOREIGN KEY(Component) REFERENCES Component(ID)' ...
        };

    tableData('Protected_Location') = { ...
        'Feature INTEGER', ...
        'Path Text', ...
        'Component INTEGER', ...
        'FOREIGN KEY(Feature) REFERENCES License(ID)', ...
        'FOREIGN KEY(Component) REFERENCES Component(ID)' ...
        };
    
    %
    % Component-level dependency tables
    %
    tableData('Required_Components') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Name Text UNIQUE', ...
        };
    
    tableData('File_Components') = { ...
        'File INTEGER', ...
        'Component INTEGER', ...
        'FOREIGN KEY(File) REFERENCES File(ID) ON DELETE CASCADE', ...
        'FOREIGN KEY(Component) REFERENCES Required_Components(ID)' ...
        };
end
