function result = mostFrequentlyUsedFileReadingTools()
% This data file contains information about most frequently call file
% reading functions and their default input file extension.
% This list covers MATLAB functions for importing data from text files,
% spread sheets, images, audio and video files, and XML files.
% 
% The data is not stored in an XML file because XMLREAD relies on Java.

persistent list

    if isempty(list)
        list = containers.Map({ 'audioinfo' ...
                                'audioread' ...
                                'csvread' ...
                                'daqread' ...
                                'dlmread' ...
                                'fileread' ...
                                'fopen' ...
                                'imfinfo' ...
                                'importdata' ...
                                'imread' ...
                                'load' ...
                                'matfile' ...
                                'mmfileinfo' ...
                                'open' ...
                                'readtable' ...
                                'type' ...
                                'VideoReader' ...
                                'xlsfinfo' ...
                                'xlsread' ...
                                'xmlread' ...
                                'xslt' ...
                              }, ...
                              { {} ... % audioinfo
                                {} ... % audioread
                                {} ... % csvread
                                {} ... % daqread
                                {} ... % dlmread
                                {} ... % fileread
                                {} ... % fopen
                                {} ... % imfinfo
                                {} ... % importdata
                                {} ... % imread
                                {'.mat'} ... % load
                                {'.mat'} ... % matfile
                                {} ... % mmfileinfo
                                {} ... % open
                                {'.txt'} ... % readtable
                                {} ... % type
                                {} ... % VideoReader
                                {'.xls' '.xlsx' '.xlsm' '.xltx' '.xltm'} ... % xlsfinfo
                                {'.xls' '.xlsx' '.xlsm' '.xltx' '.xltm'} ... % xlsread
                                {} ... % xmlread
                                {} ... % xslt
                              });
    end
    
    result = list;
end

