function figPreview = createPrintPreviewFigure()
% This undocumented helper function is for internal use.

% Creates the figure for the printpreview GUI

%   Copyright 1984-2015 The MathWorks, Inc.

figPreview = matlab.ui.Figure('Name',getString(message('MATLAB:uistring:printpreview:TitlePrintPreview')),...
    'IntegerHandle','off',...
    'Tag','TMWFigurePrintPreview',...
    'HandleVisibility','off',...
    'Interruptible','on',...
    'Renderer','opengl',...
    'units','pixels',...
    'DeleteFcn','',...
    'MenuBar','none',...
    'ToolBar','none',...
    'WindowStyle','modal',...
    'Resize','on',...
    'Visible','off',...
    'NumberTitle','off',...
    'Interruptible','off');
end
