function h = event(name,time,varargin)
%TSDATA.EVENT  Construct event object for timeseries object.
%
%    E = TSDATA.EVENT(Name,Time) creates an event object with the specified 
%    name that occurs at the time Time. Time can either be a real value or
%    a date string.
%
%    E = TSDATA.EVENT(Name,Time,'Datenum') uses 'Datenum' to indicate that
%    the Time value is a serial date number generated by the datenum function.
%    The Time value is converted to a date string after the event is
%    created.

% Copyright 2004-2016 The MathWorks, Inc.

h = tsdata.event;
if nargin==0
  return
end

if nargin>=1
  % Set the name
  if ischar(name) || isstring(name)
      h.Name = char(name);
  else
    error(message('MATLAB:tsdata:event:event:misname'))
  end
end

if nargin>=2
     % Numeric value
      if isnumeric(time) && length(time)==1
          % If there is a third input argument called 'datenum', treat the
          % numeric value as a datenum value supported by MATLAB
          if nargin == 3
              if strcmpi(varargin{1},'datenum')
                  h.Time = 0;
                  h.Units = 'days';
                  try
                      h.StartDate = datestr(time,0);
                  catch
                      error(message('MATLAB:tsdata:event:event:datenum'))
                  end
              else
                    h.Time = time;
              end
          % Otherwise, treat the numeric value as a relative time point
          else
              h.Time = time;
              h.Units = 'seconds';
          end
      % string which represent an absolute date
      elseif ischar(time) || (isstring(time) && isscalar(string))
         try 
              Time = datenum(char(time));
         catch
             error(message('MATLAB:tsdata:event:event:noValidDateStr'))
         end
         h.Time = 0;
         h.Units = 'days';
         h.StartDate = datestr(Time,0);
     else
         error(message('MATLAB:tsdata:event:event:abstime'))
     end
end

