classdef TbbhistBuildable < coder.ExternalDependency %#codegen
    %TBBHISTBUILDABLE - encapsulate tbbhist implementation library
    
    % Copyright 2013-2017 The MathWorks, Inc.
    
    
    methods (Static)
        
        function name = getDescriptiveName(~)
            name = 'TbbhistBuildable';
        end
        
        function b = isSupportedContext(context)
            b = context.isMatlabHostTarget();
        end
        
        function updateBuildInfo(buildInfo, context)
            % File extensions
            [~, linkLibExt, execLibExt] = ...
                context.getStdLibInfo();
            group = 'BlockModules';
            
            % Header paths
            buildInfo.addIncludePaths(fullfile(matlabroot,'extern','include'));
            
            % Platform specific link and non-build files
            arch      = computer('arch');
            binArch   = fullfile(matlabroot,'bin',arch,filesep);
            sysOSArch = fullfile(matlabroot,'sys','os',arch,filesep);

            switch arch
                case {'win32','win64'}
                    linkFiles     = {'libmwtbbhist'}; %#ok<*EMCA>
                    linkFiles     = strcat(linkFiles, linkLibExt);
                    libDir        = images.internal.getImportLibDirName(context);
                    linkLibPath   = fullfile(matlabroot,'extern','lib',computer('arch'),libDir);
                    nonBuildFiles = {'libmwtbbhist', 'tbb','tbbmalloc'};
                    nonBuildFiles = strcat(binArch,nonBuildFiles, execLibExt);
                    
                case {'glnxa64','maci64'}
                    linkFiles     = {'mwtbbhist'}; %#ok<*EMCA>
                    linkLibPath   = binArch;
                    
                    % Non-build files
                    if strcmp(arch,'glnxa64')
                        libstdcpp          = strcat(sysOSArch,{'libstdc++.so.6'});
                        nonBuildFilesNoExt = {'libtbb.so.2'};
                        nonBuildFilesNoExt{end+1} = 'libtbbmalloc.so.2';
                        nonBuildFilesNoExt = strcat(binArch,nonBuildFilesNoExt);
                    else
                        libstdcpp          = [];
                        nonBuildFilesNoExt = {'libtbb'};
                        nonBuildFilesNoExt{end+1} = 'libtbbmalloc';
                        nonBuildFilesNoExt = strcat(binArch,nonBuildFilesNoExt, execLibExt);
                    end
                    
                    nonBuildFilesExt = {'libmwtbbhist'};
                    nonBuildFilesExt = strcat(binArch,nonBuildFilesExt, execLibExt);
                    nonBuildFiles = [libstdcpp nonBuildFilesExt nonBuildFilesNoExt];
                    
                otherwise
                    % unsupported
                    assert(false,[arch ' operating system not supported']);
            end

            if coder.internal.hostSupportsGccLikeSysLibs()
                buildInfo.addSysLibs(linkFiles, linkLibPath, group);
            else
                linkPriority    = images.internal.coder.buildable.getLinkPriority('tbb');
                linkPrecompiled = true;
                linkLinkonly    = true;
                buildInfo.addLinkObjects(linkFiles,linkLibPath,linkPriority,...
                                         linkPrecompiled,linkLinkonly,group);
            end
            
            % Non-build files
            buildInfo.addNonBuildFiles(nonBuildFiles,'',group);
                        
        end
        
        function [out, rngFlag, nanFlag] = tbbhistcore_uint8(a, numelA, numRows, numCols, out, numelOut, numBins, rngFlag, nanFlag)
            coder.inline('always');
            coder.cinclude('libmwtbbhist.h');
            coder.ceval('-layout:any','tbbhist_uint8',...
                coder.rref(a),...
                numelA,...
                numRows,...
                numCols,...
                coder.ref(out),...
                numelOut,...
                numBins,...
                coder.ref(rngFlag),...
                coder.ref(nanFlag));
        end
        
        function [out, rngFlag, nanFlag] = tbbhistcore_uint8_scaled(a, numelA, numRows, numCols, out, numelOut, maxVal, numBins, rngFlag, nanFlag)
            coder.inline('always');
            coder.cinclude('libmwtbbhist.h');
            coder.ceval('-layout:any','tbbhist_uint8_scaled',...
                coder.rref(a),...
                numelA,...
                numRows,...
                numCols,...
                coder.ref(out),...
                numelOut,...
                maxVal,...
                numBins,...
                coder.ref(rngFlag),...
                coder.ref(nanFlag));
        end
        
        
        function [out, rngFlag, nanFlag] = tbbhistcore_uint16(a, numelA, numRows, numCols, out, numelOut, numBins, rngFlag, nanFlag)
            coder.inline('always');
            coder.cinclude('libmwtbbhist.h');
            coder.ceval('-layout:any','tbbhist_uint16',...
                coder.rref(a),...
                numelA,...
                numRows,...
                numCols,...
                coder.ref(out),...
                numelOut,...
                numBins,...
                coder.ref(rngFlag),...
                coder.ref(nanFlag));
        end
        
        function [out, rngFlag, nanFlag] = tbbhistcore_uint16_scaled(a, numelA, numRows, numCols, out, numelOut, maxVal, numBins, rngFlag, nanFlag)
            coder.inline('always');
            coder.cinclude('libmwtbbhist.h');
            coder.ceval('-layout:any','tbbhist_uint16_scaled',...
                coder.rref(a),...
                numelA,...
                numRows,...
                numCols,...
                coder.ref(out),...
                numelOut,...
                maxVal,...
                numBins,...
                coder.ref(rngFlag),...
                coder.ref(nanFlag));
        end
        
        
        function [out, rngFlag, nanFlag] = tbbhistcore_uint32_scaled(a, numelA, numRows, numCols, out, numelOut, maxVal, numBins, rngFlag, nanFlag)
            coder.inline('always');
            coder.cinclude('libmwtbbhist.h');
            coder.ceval('-layout:any','tbbhist_uint32_scaled',...
                coder.rref(a),...
                numelA,...
                numRows,...
                numCols,...
                coder.ref(out),...
                numelOut,...
                maxVal,...
                numBins,...
                coder.ref(rngFlag),...
                coder.ref(nanFlag));
        end
        
        
        function [out, rngFlag, nanFlag] = tbbhistcore_single(a, numelA, numRows, numCols, out, numelOut, numBins, rngFlag, nanFlag)
            coder.inline('always');
            coder.cinclude('libmwtbbhist.h');
            coder.ceval('-layout:any','tbbhist_real32',...
               coder.rref(a),...
                numelA,...
                numRows,...
                numCols,...
                coder.ref(out),...
                numelOut,...
                numBins,...
                coder.ref(rngFlag),...
                coder.ref(nanFlag));
        end
        
        
        function [out, rngFlag, nanFlag] = tbbhistcore_single_scaled(a, numelA, numRows, numCols, out, numelOut, maxVal, numBins, rngFlag, nanFlag)
            coder.inline('always');
            coder.cinclude('libmwtbbhist.h');
            coder.ceval('-layout:any','tbbhist_real32_scaled',...
               coder.rref(a),...
                numelA,...
                numRows,...
                numCols,...
                coder.ref(out),...
                numelOut,...
                maxVal,...
                numBins,...
                coder.ref(rngFlag),...
                coder.ref(nanFlag));
        end
        
        
        function [out, rngFlag, nanFlag] = tbbhistcore_double(a, numelA, numRows, numCols, out, numelOut, numBins, rngFlag, nanFlag)
            coder.inline('always');
            coder.cinclude('libmwtbbhist.h');
            coder.ceval('-layout:any','tbbhist_real64',...
                coder.rref(a),...
                numelA,...
                numRows,...
                numCols,...
                coder.ref(out),...
                numelOut,...
                numBins,...
                coder.ref(rngFlag),...
                coder.ref(nanFlag));
        end
        
        
        function [out, rngFlag, nanFlag] = tbbhistcore_double_scaled(a, numelA, numRows, numCols, out, numelOut, maxVal, numBins, rngFlag, nanFlag)
            coder.inline('always');
            coder.cinclude('libmwtbbhist.h');
            coder.ceval('-layout:any','tbbhist_real64_scaled',...
                coder.rref(a),...
                numelA,...
                numRows,...
                numCols,...
                coder.ref(out),...
                numelOut,...
                maxVal,...
                numBins,...
                coder.ref(rngFlag),...
                coder.ref(nanFlag));
        end
        
        
    end
    
    
end
