function renderToolbars(this)

% Copyright 2017 The MathWorks, Inc.

% Add the Export to IMTool toolbar button.
this.IMToolExporterButton = uipushtool( ...
    this.Application.Handles.mainToolbar, ...
    'Tag','uimgr.uipushtool_IMToolExporter', ...
    'BusyAction', 'cancel', ...
    'Interruptible', 'off', ...
    'Tooltip', getString(message('images:implayUIString:exportToImageToolTooltip')), ...
    'Click', @(hco,ev) lclExport(this), ...
    'CData', this.Application.getIcon('export_to_imtool'), ...
    'Separator','on');
