classdef InvalidFatalAssertionDelegate < matlab.unittest.internal.qualifications.FatalAssertionDelegate & ...
                                     matlab.unittest.internal.qualifications.InvalidDelegateMixin
end