classdef InvalidAssumptionDelegate < matlab.unittest.internal.qualifications.AssumptionDelegate & ...
                                     matlab.unittest.internal.qualifications.InvalidDelegateMixin
end