classdef InvalidAssertionDelegate < matlab.unittest.internal.qualifications.AssertionDelegate & ...
                                     matlab.unittest.internal.qualifications.InvalidDelegateMixin
end