classdef LegendDialog < dialogmgr.DialogContent
    % Implement legend dialog for NTX

%   Copyright 2010-2012 The MathWorks, Inc.
    
    properties (Access=private)
        % Handles to widgets within the main dialog panel
        htNormalText
        htNormalBar
        htOverflowText
        htOverflowBar
        htUnderflowText
        htUnderflowBar
    end
    
    methods
        function dlg = LegendDialog(ntx)
            dlg.Name = getString(message('fixed:NumericTypeScope:LegendDialogName'));
            dlg.UserData = ntx; % record NTX application handle
        end
    end
    
    methods (Access=protected)
        function createContent(dlg)
            % Widgets within dialog are created in this method
            %
            % All widgets should be parented to hParent, or to a
            % child of hParent.
            
            hParent = dlg.ContentPanel;
            set(hParent,'Tag','legend_dialog_panel');
            bg = get(hParent,'BackgroundColor');
            ppos = get(hParent,'Position');
            pdx = ppos(3); % initial width of parent panel, in pixels
            
            ntx = dlg.UserData;
                        
            yB = 8; % # pix between border and widgets
            xB = 8; % # pix between border and widgets
            xG = 6; % # pix between bars and text
            pdx2 = floor(pdx/2); % midpoint
            xL = xB;
            dxL = pdx2-xB-xG/2;
            xR = xB+dxL+xG; % 1-pix gap to start of xR
            dxR = pdx-xR-xB;
            
            dy=14 * ntx.dp.PixelFactor;
            y0=1-dy-4;
            
            y0=y0+dy+4;
            dlg.htUnderflowBar = uicontrol( ...
                'Parent', hParent, ...
                'BackgroundColor',ntx.ColorUnderflowBar, ...
                'ForegroundColor','k', ...
                'Units','pix', ...
                'Position', [xL y0+yB dxL dy], ...
                'Enable','inactive', ...
                'Tag','legend_underflow_frame',...
                'Style','frame'); 
            dlg.htUnderflowText = uicontrol( ...
                'Parent', hParent, ...
                'BackgroundColor', bg, ...
                'Units','pix', ...
                'HorizontalAlignment','left', ...
                'Position', [xR y0+yB dxR dy], ...
                'Enable','inactive', ...
                'Style','text', ...
                'Tag','legend_underflow_text',...
                'String',getString(message('fixed:NumericTypeScope:UI_BelowPrecisionStr')));
            
            y0=y0+dy+4;
            %tip = sprintf([ ...
            %    'Histogram bar color representing data values\n' ...
            %    'representable by suggested numeric type.']);
            dlg.htNormalBar = uicontrol( ...
                'Parent', hParent, ...
                'BackgroundColor',ntx.ColorNormalBar, ...
                'ForegroundColor','k', ...
                'Units','pix', ...
                'Position', [xL y0+yB dxL dy], ...
                'Enable','inactive', ...
                'Tag','legend_inrange_frame',...
                'Style','frame'); 
            dlg.htNormalText = uicontrol( ...
                'Parent', hParent, ...
                'BackgroundColor', bg, ...
                'Units','pix', ...
                'HorizontalAlignment','left', ...
                'Position', [xR y0+yB dxR dy], ...
                'Enable','inactive', ...
                'Tag','legend_inrange_text',...
                'Style','text', ...
                'String',getString(message('fixed:NumericTypeScope:UI_InRangeStr')));
            
            y0=y0+dy+4;
            %tip = sprintf([ ...
            %    'Histogram bar color representing data values\n' ...
            %    'exceeding range of suggested numeric type.']);
            dlg.htOverflowBar = uicontrol( ...
                'Parent', hParent, ...
                'BackgroundColor',ntx.ColorOverflowBar, ...
                'ForegroundColor','k', ...
                'Units','pix', ...
                'Position', [xL y0+yB dxL dy], ...
                'Enable','inactive', ...
                'Tag','legend_overflow_frame',...
                'Style','frame'); 
            dlg.htOverflowText = uicontrol( ...
                'Parent', hParent, ...
                'BackgroundColor', bg, ...
                'Units','pix', ...
                'HorizontalAlignment','left', ...
                'Position', [xR y0+yB dxR dy], ...
                'Enable','inactive', ...
                'Style','text', ...
                'Tag','legend_overflow_text',...
                'String',getString(message('fixed:NumericTypeScope:UI_OutsideRangeStr')));
            
            % Final height
            pdy = y0+dy+4+yB; % final height, add ~1 char for label
            set(hParent,'Position',[1 1 pdx pdy]);
        end
    end
end
