function scriptString = createReportHeaderJs
scriptString = ['<script type="text/javascript" language="JavaScript">'...
    'function toggleexpander(blockid) {'...
   'block = document.getElementById(blockid);'...
   'showMore = document.getElementById(blockid+"_button");'...
   'arrow = document.getElementById(blockid+"_arrow");'...
   'if (block.style.display === undefined || block.style.display == "undefined" || block.style.display == "")'...
    '{'...
     'block.style.display = "none";'...
    '}'...
    'if (block.style.display == "none")'...
    '{'...
     'block.style.display = "block";'...
     'showMore.innerHTML="show less";'...
     'arrow.src="file://"+arrow_open;'...
    '}'...
    'else'...
    '{'...
     'block.style.display = "none";'...
     'showMore.innerHTML="show more";'...
     'arrow.src="file://"+arrow_closed;'...
    '}'...
'}'...
'function setRegexpPref(val) {'...
    'var command = "internal.matlab.reports.setDoFixRegexp(''" + val + "'')";'...
    'runMatlab(command);'...
'}'...
'function runMatlab(command) {'...
    'document.location = "matlab:" + command;'...
'}'...
'function runreport(reportcommand) {'...
    'document.location="matlab:" + reportcommand;'...
'}'...
    '</script>'];
end

