//>>built
require({cache:{"dojo/require":function(){define(["./_base/loader"],function(d){return{dynamic:0,normalize:function(c){return c},load:d.require}})},"dojo/selector/lite":function(){define(["../has","../_base/kernel"],function(d,c){var g=document.createElement("div"),b=g.matches||g.webkitMatchesSelector||g.mozMatchesSelector||g.msMatchesSelector||g.oMatchesSelector,f=g.querySelectorAll,l=/([^\s,](?:"(?:\\.|[^"])+"|'(?:\\.|[^'])+'|[^,])*)/g;d.add("dom-matches-selector",!!b);d.add("dom-qsa",!!f);var a=
function(l,n){if(k&&-1<l.indexOf(","))return k(l,n);var p=n?n.ownerDocument||n:c.doc||document,b=(f?/^([\w]*)#([\w\-]+$)|^(\.)([\w\-\*]+$)|^(\w+$)/:/^([\w]*)#([\w\-]+)(?:\s+(.*))?$|(?:^|(>|.+\s+))([\w\-\*]+)(\S*$)/).exec(l);n=n||p;if(b){var g=8===d("ie")&&d("quirks")?n.nodeType===p.nodeType:null!==n.parentNode&&9!==n.nodeType&&n.parentNode===p;if(b[2]&&g){var r=c.byId?c.byId(b[2],p):p.getElementById(b[2]);if(!r||b[1]&&b[1]!=r.tagName.toLowerCase())return[];if(n!=p)for(p=r;p!=n;)if(p=p.parentNode,
!p)return[];return b[3]?a(b[3],r):[r]}if(b[3]&&n.getElementsByClassName)return n.getElementsByClassName(b[4]);if(b[5])if(r=n.getElementsByTagName(b[5]),b[4]||b[6])l=(b[4]||"")+b[6];else return r}if(f)return 1===n.nodeType&&"object"!==n.nodeName.toLowerCase()?h(n,l,n.querySelectorAll):n.querySelectorAll(l);r||(r=n.getElementsByTagName("*"));b=[];p=0;for(g=r.length;p<g;p++){var w=r[p];1==w.nodeType&&e(w,l,n)&&b.push(w)}return b},h=function(a,b,e){var c=a,f=a.getAttribute("id"),d=f||"__dojo__",k=a.parentNode,
g=/^\s*[+~]/.test(b);if(g&&!k)return[];f?d=d.replace(/'/g,"\\$\x26"):a.setAttribute("id",d);g&&k&&(a=a.parentNode);b=b.match(l);for(k=0;k<b.length;k++)b[k]="[id\x3d'"+d+"'] "+b[k];b=b.join(",");try{return e.call(a,b)}finally{f||c.removeAttribute("id")}};if(!d("dom-matches-selector"))var e=function(){function a(b,q,e){var l=q.charAt(0);if('"'==l||"'"==l)q=q.slice(1,-1);q=q.replace(/\\/g,"");var c=d[e||""];return function(a){return(a=a.getAttribute(b))&&c(a,q)}}function b(a){return function(b,e){for(;(b=
b.parentNode)!=e;)if(a(b,e))return!0}}function e(a){return function(b,e){b=b.parentNode;return a?b!=e&&a(b,e):b==e}}function l(a,b){return a?function(e,l){return b(e)&&a(e,l)}:b}var c="div"==g.tagName?"toLowerCase":"toUpperCase",f={"":function(a){a=a[c]();return function(b){return b.tagName==a}},".":function(a){var b=" "+a+" ";return function(e){return-1<e.className.indexOf(a)&&-1<(" "+e.className+" ").indexOf(b)}},"#":function(a){return function(b){return b.id==a}}},d={"^\x3d":function(a,b){return 0==
a.indexOf(b)},"*\x3d":function(a,b){return-1<a.indexOf(b)},"$\x3d":function(a,b){return a.substring(a.length-b.length,a.length)==b},"~\x3d":function(a,b){return-1<(" "+a+" ").indexOf(" "+b+" ")},"|\x3d":function(a,b){return 0==(a+"-").indexOf(b+"-")},"\x3d":function(a,b){return a==b},"":function(a,b){return!0}},k={};return function(c,d,g){var h=k[d];if(!h){if(d.replace(/(?:\s*([> ])\s*)|(#|\.)?((?:\\.|[\w-])+)|\[\s*([\w-]+)\s*(.?=)?\s*("(?:\\.|[^"])+"|'(?:\\.|[^'])+'|(?:\\.|[^\]])*)\s*\]/g,function(c,
d,k,g,t,x,q){g?h=l(h,f[k||""](g.replace(/\\/g,""))):d?h=(" "==d?b:e)(h):t&&(h=l(h,a(t,q,x)));return""}))throw Error("Syntax error in query");if(!h)return!0;k[d]=h}return h(c,g)}}();if(!d("dom-qsa"))var k=function(b,e){for(var c=b.match(l),d=[],f=0;f<c.length;f++){b=new String(c[f].replace(/\s*$/,""));b.indexOf=escape;for(var k=a(b,e),g=0,h=k.length;g<h;g++){var s=k[g];d[s.sourceIndex]=s}}c=[];for(f in d)c.push(d[f]);return c};a.match=b?function(a,e,c){return c&&9!=c.nodeType?h(c,e,function(e){return b.call(a,
e)}):b.call(a,e)}:e;return a})},"xstyle/core/load-css":function(){define([],function(){function d(c){if(b.createStyleSheet){var a=b.createStyleSheet();a.cssText=c;return a.owningElement}a=b.createElement("style");a.setAttribute("type","text/css");a.appendChild(b.createTextNode(c));f.insertBefore(a,f.firstChild);return a}function c(c,a,h){var e=g[c];if(e)return k=d(e),a(k);var k=b.createElement("link");k.type="text/css";k.rel="stylesheet";k.href=c;var v=!h||!1!==h.wait;h=(h=navigator.userAgent.match(/AppleWebKit\/(\d+\.?\d*)/))&&
+h[1];if(null===k.onload&&!(536>h))k.onload=function(){k.onload=null;k.onerror=null;v&&a(k)},k.onerror=function(){console.error("Error loading stylesheet "+c);v&&a(k)};else if(v)var n=setInterval(function(){k.style&&(clearInterval(n),a(k))},15);(f||b.getElementsByTagName("head")[0]).appendChild(k);v||a(k)}var g="undefined"==typeof _css_cache?{}:_css_cache,b=document,f=b.head;c.insertCss=d;return c})},"dijit/main":function(){define(["dojo/_base/kernel"],function(d){return d.dijit})},"dojox/main":function(){define(["dojo/_base/kernel"],
function(d){return d.dojox})},"mw-browser-utils/BrowserCheck":function(){define("dojo/_base/window dojo/window dojo/dom-construct dojo/has dojo/i18n!./l10n/nls/unsupportedErrorPage ./detect/css ./detect/object".split(" "),function(d,c,g,b,f){var l={isBrowserValid:function(){var a=!0;b("quirks")?a=!1:b("css-enabled")?b("css-border-radius")?b("css-text-overflow")?b("object-create")||(a=!1):a=!1:a=!1:a=!1;return a},displayErrorAsOverlay:function(){g.create("div",{style:{position:"absolute",left:"0%",
top:"0%","background-color":"grey","-moz-opacity":"0.7",opacity:".70",filter:"alpha(opacity\x3d70)",width:"100%",height:"100%",zIndex:"90"},id:"fadeDiv"},d.body());g.create("div",{style:{position:"relative",margin:"auto","margin-top":"12.35%",width:"400px",height:"300px",padding:"10px",border:"2px solid black","background-color":"#ffffff","z-index":"100","font-family":"Sans-serif"},id:"unsupportedBrowser","class":"content_module"},d.body()).innerHTML=f.unsupportedError}};return{load:function(a,b,
e){l.isBrowserValid()?e():a?d.global.location=a:l.displayErrorAsOverlay()}}})},"dojo/window":function(){define("./_base/lang ./sniff ./_base/window ./dom ./dom-geometry ./dom-style ./dom-construct".split(" "),function(d,c,g,b,f,l,a){c.add("rtl-adjust-position-for-verticalScrollBar",function(b,c){var d=g.body(c),l=a.create("div",{style:{overflow:"scroll",overflowX:"visible",direction:"rtl",visibility:"hidden",position:"absolute",left:"0",top:"0",width:"64px",height:"64px"}},d,"last"),p=a.create("div",
{style:{overflow:"hidden",direction:"ltr"}},l,"last"),h=0!=f.position(p).x;l.removeChild(p);d.removeChild(l);return h});c.add("position-fixed-support",function(b,c){var d=g.body(c),l=a.create("span",{style:{visibility:"hidden",position:"fixed",left:"1px",top:"1px"}},d,"last"),p=a.create("span",{style:{position:"fixed",left:"0",top:"0"}},l,"last"),h=f.position(p).x!=f.position(l).x;l.removeChild(p);d.removeChild(l);return h});var h={getBox:function(a){a=a||g.doc;var b="BackCompat"==a.compatMode?g.body(a):
a.documentElement,d=f.docScroll(a);if(c("touch")){var l=h.get(a);a=l.innerWidth||b.clientWidth;b=l.innerHeight||b.clientHeight}else a=b.clientWidth,b=b.clientHeight;return{l:d.x,t:d.y,w:a,h:b}},get:function(a){if(c("ie")&&h!==document.parentWindow){a.parentWindow.execScript("document._parentWindow \x3d window;","Javascript");var b=a._parentWindow;a._parentWindow=null;return b}return a.parentWindow||a.defaultView},scrollIntoView:function(a,d){try{a=b.byId(a);var h=a.ownerDocument||g.doc,n=g.body(h),
p=h.documentElement||n.parentNode,y=c("ie")||c("trident"),A=c("webkit");if(!(a==n||a==p))if(!c("mozilla")&&(!y&&!A&&!c("opera")&&!c("trident")&&!c("edge"))&&"scrollIntoView"in a)a.scrollIntoView(!1);else{var r="BackCompat"==h.compatMode,w=Math.min(n.clientWidth||p.clientWidth,p.clientWidth||n.clientWidth),B=Math.min(n.clientHeight||p.clientHeight,p.clientHeight||n.clientHeight),h=A||r?n:p,s=d||f.position(a),q=a.parentNode,A=function(a){return 6>=y||7==y&&r?!1:c("position-fixed-support")&&"fixed"==
l.get(a,"position").toLowerCase()},E=this,G=function(a,b,c){"BODY"==a.tagName||"HTML"==a.tagName?E.get(a.ownerDocument).scrollBy(b,c):(b&&(a.scrollLeft+=b),c&&(a.scrollTop+=c))};if(!A(a))for(;q;){q==n&&(q=h);var m=f.position(q),D=A(q),F="rtl"==l.getComputedStyle(q).direction.toLowerCase();if(q==h){m.w=w;m.h=B;if(h==p&&(y||c("trident"))&&F)m.x+=h.offsetWidth-m.w;m.x=0;m.y=0}else{var C=f.getPadBorderExtents(q);m.w-=C.w;m.h-=C.h;m.x+=C.l;m.y+=C.t;var t=q.clientWidth,x=m.w-t;0<t&&0<x&&(F&&c("rtl-adjust-position-for-verticalScrollBar")&&
(m.x+=x),m.w=t);t=q.clientHeight;x=m.h-t;0<t&&0<x&&(m.h=t)}D&&(0>m.y&&(m.h+=m.y,m.y=0),0>m.x&&(m.w+=m.x,m.x=0),m.y+m.h>B&&(m.h=B-m.y),m.x+m.w>w&&(m.w=w-m.x));var H=s.x-m.x,I=s.y-m.y,K=H+s.w-m.w,L=I+s.h-m.h,u,z;if(0<K*H&&(q.scrollLeft||q==h||q.scrollWidth>q.offsetHeight)){u=Math[0>H?"max":"min"](H,K);if(F&&(8==y&&!r||5<=c("trident")))u=-u;z=q.scrollLeft;G(q,u,0);u=q.scrollLeft-z;s.x-=u}if(0<L*I&&(q.scrollTop||q==h||q.scrollHeight>q.offsetHeight))u=Math.ceil(Math[0>I?"max":"min"](I,L)),z=q.scrollTop,
G(q,0,u),u=q.scrollTop-z,s.y-=u;q=q!=h&&!D&&q.parentNode}}}catch(J){console.error("scrollIntoView: "+J),a.scrollIntoView(!1)}}};d.setObject("dojo.window",h);return h})},"dojo/i18n":function(){define("./_base/kernel require ./has ./_base/array ./_base/config ./_base/lang ./_base/xhr ./json module".split(" "),function(d,c,g,b,f,l,a,h,e){g.add("dojo-preload-i18n-Api",1);var k=d.i18n={},v=/(^.*(^|\/)nls)(\/|$)([^\/]*)\/?([^\/]*)/,n=function(a,b,c,d){var l=[c+d];b=b.split("-");for(var f="",e=0;e<b.length;e++)if(f+=
(f?"-":"")+b[e],!a||a[f])l.push(c+f+"/"+d),l.specificity=f;return l},p={},y=function(a,b,c){c=c?c.toLowerCase():d.locale;a=a.replace(/\./g,"/");b=b.replace(/\./g,"/");return/root/i.test(c)?a+"/nls/"+b:a+"/nls/"+c+"/"+b},A=d.getL10nName=function(a,b,c){return e.id+"!"+y(a,b,c)},r=function(a,b,c,d,f,e){a([b],function(g){var h=l.clone(g.root||g.ROOT),k=n(!g._v1x&&g,f,c,d);a(k,function(){for(var a=1;a<k.length;a++)h=l.mixin(l.clone(h),arguments[a]);p[b+"/"+f]=h;h.$locale=k.specificity;e()})})},w=function(a){var b=
f.extraLocale||[],b=l.isArray(b)?b:[b];b.push(a);return b},B=function(a,c,f){if(g("dojo-preload-i18n-Api")){var e=a.split("*"),k="preload"==e[1];k&&(p[a]||(p[a]=1,G(e[2],h.parse(e[3]),1,c)),f(1));if(!(e=k))q&&E.push([a,c,f]),e=q;if(e)return}a=v.exec(a);var n=a[1]+"/",u=a[5]||a[4],z=n+u,e=(a=a[5]&&a[4])||d.locale||"",J=z+"/"+e;a=a?[e]:w(e);var M=a.length,s=function(){--M||f(l.delegate(p[J]))};b.forEach(a,function(a){var b=z+"/"+a;g("dojo-preload-i18n-Api")&&m(b);p[b]?s():r(c,z,n,u,a,s)})};g("dojo-preload-i18n-Api");
var s=k.normalizeLocale=function(a){a=a?a.toLowerCase():d.locale;return"root"==a?"ROOT":a},q=0,E=[],G=k._preloadLocalizations=function(a,f,e,g){function h(a,b){g.isXdUrl(c.toUrl(a+".js"))||e?g([a],b):C([a],b,g)}function k(a,b){for(var c=a.split("-");c.length;){if(b(c.join("-")))return;c.pop()}b("ROOT")}function m(){for(--q;!q&&E.length;)B.apply(null,E.shift())}function n(d){d=s(d);k(d,function(e){if(0<=b.indexOf(f,e)){var n=a.replace(/\./g,"/")+"_"+e;q++;h(n,function(a){for(var b in a){var f=a[b],
h=b.match(/(.+)\/([^\/]+)$/),n;if(h&&(n=h[2],h=h[1]+"/",f._localized)){var t;if("ROOT"===e){var x=t=f._localized;delete f._localized;x.root=f;p[c.toAbsMid(b)]=x}else t=f._localized,p[c.toAbsMid(h+n+"/"+e)]=f;e!==d&&function(a,b,f,e){var h=[],n=[];k(d,function(f){e[f]&&(h.push(c.toAbsMid(a+f+"/"+b)),n.push(c.toAbsMid(a+b+"/"+f)))});h.length?(q++,g(h,function(){for(var e=h.length-1;0<=e;e--)f=l.mixin(l.clone(f),arguments[e]),p[n[e]]=f;p[c.toAbsMid(a+b+"/"+d)]=l.clone(f);m()})):p[c.toAbsMid(a+b+"/"+
d)]=f}(h,n,f,t)}}m()});return!0}return!1})}g=g||c;n();b.forEach(d.config.extraLocale,n)},m=function(){},D={},F=new Function("__bundle","__checkForLegacyModules","__mid","__amdValue","var define \x3d function(mid, factory){define.called \x3d 1; __amdValue.result \x3d factory || mid;},\t   require \x3d function(){define.called \x3d 1;};try{define.called \x3d 0;eval(__bundle);if(define.called\x3d\x3d1)return __amdValue;if((__checkForLegacyModules \x3d __checkForLegacyModules(__mid)))return __checkForLegacyModules;}catch(e){}try{return eval('('+__bundle+')');}catch(e){return e;}"),
C=function(c,f,e){var d=[];b.forEach(c,function(b){function c(a){a=F(a,m,b,D);a===D?d.push(p[f]=D.result):(a instanceof Error&&(console.error("failed to evaluate i18n bundle; url\x3d"+f,a),a={}),d.push(p[f]=/nls\/[^\/]+\/[^\/]+$/.test(f)?a:{root:a,_v1x:1}))}var f=e.toUrl(b+".js");if(p[f])d.push(p[f]);else{var l=e.syncLoadNls(b);l||(l=m(b.replace(/nls\/([^\/]*)\/([^\/]*)$/,"nls/$2/$1")));if(l)d.push(l);else if(a)a.get({url:f,sync:!0,load:c,error:function(){d.push(p[f]={})}});else try{e.getText(f,!0,
c)}catch(h){d.push(p[f]={})}}});f&&f.apply(null,d)},m=function(a){for(var b,c=a.split("/"),f=d.global[c[0]],e=1;f&&e<c.length-1;f=f[c[e++]]);f&&((b=f[c[e]])||(b=f[c[e].replace(/-/g,"_")]),b&&(p[a]=b));return b};k.getLocalization=function(a,b,f){var e;a=y(a,b,f);B(a,!c.isXdUrl(c.toUrl(a+".js"))?function(a,b){C(a,b,c)}:c,function(a){e=a});return e};return l.mixin(k,{dynamic:!0,normalize:function(a,b){return/^\./.test(a)?b(a):a},load:B,cache:p,getL10nName:A})})},"mw-browser-utils/detect/css":function(){define(["dojo/has"],
function(d){function c(b,c){var a=!1,d=b.charAt(0).toUpperCase()+b.slice(1),e=g.length,k=c.style;if("string"===typeof k[b])a=!0;else for(;e;)if(e-=1,"string"===typeof k[g[e]+d]){a=!0;break}return a}var g=["Webkit","Moz","O","ms","Khtml"],b=d.add;b("css-enabled",function(b,c,a){var d;b=c.documentElement;var e;if(!(e=c.body))d=!0,e=b.insertBefore(c.createElement("body"),b.firstChild);b=e;e=a.style.display;a.style.display="none";b.insertBefore(a,b.firstChild);c=0===a.offsetWidth;b.removeChild(a);a.style.display=
e;d&&b.parentNode.removeChild(b);return c});b("css-content-box",function(b,c,a){var h,e;b=c.documentElement;var g=null;if(d("css-enabled")){if(!(e=c.body))h=!0,e=b.insertBefore(c.createElement("body"),b.firstChild);a.style.cssText="position: absolute; top: -4000px; width: 40px; height: 40px; border: 1px solid black;";e.insertBefore(a,e.firstChild);g=40===a.clientWidth;e.removeChild(a);a.style.cssText=""}h&&e.parentNode.removeChild(e);return g});b("css-position-fixed",function(b,c,a){var g,e,k=c.documentElement,
v=null;if(d("css-enabled")){b=a.cloneNode(!1);if(!(e=c.body))g=!0,e=k.insertBefore(c.createElement("body"),k.firstChild);c=e.style.cssText;e.style.cssText="padding:0;margin:0";a.style.cssText="position:fixed;top:42px";e.insertBefore(b,e.firstChild);e.insertBefore(a,b);v=a.offsetTop!==b.offsetTop;e.removeChild(a);e.removeChild(b);e.style.cssText=c;a.style.cssText=""}g&&e.parentNode.removeChild(e);return v});b("css-rgba",function(b,c,a){b=/^rgba/;c=null;if(d("css-enabled"))try{a.style.color="rgba(1,1,1,0.5)",
c=b.test(a.style.color),a.style.color=""}catch(g){}return c});b("css-border-radius",function(b,d,a){return c("borderRadius",a)});b("css-box-shadow",function(b,d,a){return c("boxShadow",a)});b("css-box-sizing",function(b,d,a){return c("boxSizing",a)});b("css-opacity",function(b,d,a){return c("opacity",a)});b("css-opacity-filter",function(b,c){return!d("css-opacity")&&"undefined"!==typeof c.documentElement.filters});b("css-resize",function(b,d,a){return c("resize",a)});b("css-selectable",function(b,
d,a){return c("userSelect",a)});b("css-style-float",function(b,d,a){return c("styleFloat",a)});b("css-pointerevents",function(b,d,a){return c("pointerEvents",a)});b("css-text-overflow",function(b,d,a){return c("textOverflow",a)});b("css-text-shadow",function(b,d,a){return c("textShadow",a)});b("css-transform",function(b,d,a){return c("transform",a)});return d})},"mw-browser-utils/detect/object":function(){define(["dojo/has"],function(d){var c=d.add,g={}.toString,b=Object;c("object-create",function(){return"[object Function]"===
g.call(b.create)});c("object-getprototypeof",function(){return"[object Function]"===g.call(b.getPrototypeOf)});c("object-seal",function(){return"[object Function]"===g.call(b.seal)});c("object-freeze",function(){return"[object Function]"===g.call(b.freeze)});c("object-issealed",function(){return"[object Function]"===g.call(b.isSealed)});c("object-isfrozen",function(){return"[object Function]"===g.call(b.isFrozen)});c("object-keys",function(){return"[object Function]"===g.call(b.keys)});c("object-preventextensions",
function(){return"[object Function]"===g.call(b.preventExtensions)});c("object-isextensible",function(){return"[object Function]"===g.call(b.isExtensible)});c("object-defineproperty",function(){return"[object Function]"===g.call(b.defineProperty)});c("object-defineproperties",function(){return"[object Function]"===g.call(b.defineProperties)});c("object-getownpropertydescriptor",function(){return"[object Function]"===g.call(b.getOwnPropertyDescriptor)});c("object-getownpropertynames",function(){return"[object Function]"===
g.call(b.getOwnPropertyNames)});c("object-es5",function(){return d("object-create")&&d("object-defineproperties")&&d("object-defineproperty")&&d("object-freeze")&&d("object-getownpropertydescriptor")&&d("object-getownpropertynames")&&d("object-getprototypeof")&&d("object-isextensible")&&d("object-isfrozen")&&d("object-issealed")&&d("object-keys")&&d("object-preventextensions")&&d("object-seal")});return d})},"*now":function(d){d(['dojo/i18n!*preload*variableeditor/nls/browsercheck*["ar","ca","cs","da","de","el","en-gb","en-us","es-es","fi-fi","fr-fr","he-il","hu","it-it","ja-jp","ko-kr","nl-nl","nb","pl","pt-br","pt-pt","ru","sk","sl","sv","th","tr","zh-tw","zh-cn","ROOT"]'])}}});
define("variableeditor/browsercheck",[],1);
//# sourceMappingURL=browsercheck.js.map