function b = hasInterestingInformation(this)
% HASINTERESTINGINFORMATION Returns true if the result has information that is interesting or useful.

% Copyright 2012-2014 The MathWorks, Inc.

% Decide based on cached information when a result is updated or reset.    
    b = this.IsPlottable || ...
        this.hasMinMaxInformation ||...
        this.HasOverflowInformation || ...
        this.HasProposedDT || ...
        this.HasSpecifiedDT || ...
        this.HasAlert;
end
