classdef (Hidden) MP4AVFoundationPlugin < audiovideo.internal.writer.plugin.IPlugin
    %MP4AVFoundationPlugin Extension of the IPlugin class to write MPEG-4
    %H.264 Files on Mac OS X 10.7 and later
    
    % Copyright 2012-2017 The MathWorks, Inc.
    properties
        ColorFormat = 'RGB24';
        ColorChannels = 3;
        BitsPerPixel = 24;
    end
    
    properties(Access=protected)
        FileName;
        CustomEventListener;
    end
    
    methods
        function obj = MP4AVFoundationPlugin(fileName)
            %MP4AVFoundationPlugin Construct a MP4AVFoundationPlugin object.
            %
            %   OBJ = MP4AVFoundationPlugin(FILENAME) constructs a
            %   MP4AVFoundationPlugin object pointing to the file specified
            %   by FILENAME.  The file is not created until
            %   MP4AVFoundationPlugin.open() is called. 
            %
            %   See also MP4AVFoundationPlugin/open, MP4AVFoundationPlugin/close.
            
            obj = obj@audiovideo.internal.writer.plugin.IPlugin();
            
            % Handle the zero argument constructor.  This is needed, for
            % example, when constructing empty profile objects.
            if isempty(fileName)
                obj.Channel = [];
                return;
            end
            
            obj.FileName = fileName;
        end
        
        function set.FileName(obj, value)
            obj.FileName = value;
            
            % After setting the value, create the asyncio Channel object.
            % This is done here instead of in the constructor
            % so that the channel is initialized properly during load and
            % save
            obj.createChannel();
        end
        
        function open(obj, options)
            %OPEN Opens the channel for writing.
            %   MP4AVFoundationPlugin objects must be open prior to calling
            %   writeVideoFrame.
            obj.open@audiovideo.internal.writer.plugin.IPlugin(options);
        end
        
        function close(obj)
            obj.close@audiovideo.internal.writer.plugin.IPlugin();
        end
        
        function writeVideoFrame(obj, data)
            %writeVideoFrame Write a single video frame to the channel.
            %   obj.writeVideoFrame(data) will write a single video frame
            %   to the channel. 
            
            assert(isnumeric(data),'Data to write must be numeric');
            obj.writeVideoFrame@audiovideo.internal.writer.plugin.IPlugin(data);
        end
        
                
        function [pluginName, mlConverterName, slConverterName, options] = ...
                                                getChannelInitOptions(obj)
            %GETCHANNELINITOPTIONS options for asyncio channel creation
            %   Setup options used in createChannel function.
            %   Subclasses can override this function to provide custom
            %   plugins and options
            pluginName = 'videoavfoundationwriterplugin';
            [mlConverterName, slConverterName] = obj.getConverterName;
            options.OutputFileName = obj.FileName;
        end
       
        function [filterName, options] = getFilterInitOptions(obj)
            filterName = 'videotransformfilter';
            options.InputFrameType = 'RawPlanarColumn';
            if ~isempty(obj.Channel)
                options.OutputFrameType = obj.Channel.ExpectedFrameType;
            else
                options.OutputFrameType = '';
            end
        end

    end
    
    methods(Access=protected)
       
        function [mlErrorID, msgHoles] = deviceErrorToErrorID(~, deviceErr, deviceMsg)
            %DEVICEERRORTOERRORID conversion from Device Error ID to MATLAB
            %Error ID
            %   Convert the Error ID generated by the Device Plugin to a
            %   MATLAB Error ID. Each plugin has knowledge about the
            %   specific errors that are thrown by the corresponding Device
            %   Plugin
            msgHoles = {};
            mlPrefix =  audiovideo.internal.writer.plugin.IPlugin.ErrorPrefix;
            switch(deviceErr)
                case 'avfoundationplugin:initializationFailed'
                    mlErrorID = sprintf('%s:%s', mlPrefix, 'couldNotInitFile');
                case 'avfoundationplugin:openFailed'
                    mlErrorID = sprintf('%s:%s', mlPrefix, 'couldNotCloseFile');
                case 'avfoundationplugin:writeFailed'
                    mlErrorID = sprintf('%s:%s', mlPrefix, 'couldNotWriteFrame');
                case 'avfoundationplugin:unexpectedError'
                    mlErrorID = sprintf('%s:%s', mlPrefix, 'unexpectedErrorWithReason');
                    msgHoles = {deviceMsg};
                otherwise % unexpected error
                    mlErrorID = sprintf('%s:%s', mlPrefix, 'unexpectedError');
            end
        end
    end
end