% WEBCONTAINERCONTROLLER Base class for all MATLAB Component Framework (MCF)
% web-based container controllers. Introduced to capture commonalities across 
% all container controllers in terms of the use of MCF services, such as the          
% Property Management Service (PMS) and the Event Handling Service (EHS).
classdef WebContainerController < ...
    matlab.ui.internal.componentframework.WebComponentController & ...
    matlab.ui.internal.componentframework.services.core.identification.IdentificationService

  methods ( Access = 'public' )

     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     %
     %  Method:       Constructor
     %
     %  Inputs:       model -> Model MCOS object for the web component.
     %                varargin{1} -> Parent controller.
     %                varargin{2) -> View.
     %
     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     function obj = WebContainerController( model, varargin )
        % MATLAB Component Framework's (MCF) web-based container controller 
        % constructor.
        obj = obj@matlab.ui.internal.componentframework.WebComponentController( model, varargin{:} );
     end

  end

  methods( Access = 'protected' )

     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     %
     %  Method:      defineViewProperties                     
     %  
     %  Inputs:      None.
     %  Outputs:     None.
     %
     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     function defineViewProperties( obj )
        % By leveraging MCF's Property Management Service (PMS), properties
        % pertaining to the view can be customized per web component and the 
        % corresponding web controller.
        % This method defines view properties common to all containers.
        obj.PropertyManagementService.defineViewProperty( 'SizeChangedFcn' );
        defineViewProperties@matlab.ui.internal.componentframework.WebComponentController( obj );
     end

     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     %
     %  Method:      findModelFromChildId                     
     %
     %  Inputs:      id -> Unique identifier generated by MCF's Identification
     %                     Service.
     %  Outputs:     mcosHandle -> MCOS handle of the child found based on the
     %                             unique identifier.
     %
     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     function mcosHandle = findModelFromChildId( obj, id )
        % Finds and returns the MCOS handle based on child's unique identifier 
        % generated by MCF's Identification Service.
        mcosHandle = [];
        % Don't use obj.Model.Children in case HandleVisibility is off - g1504402
        children = allchild(obj.Model); 
        for idx=1:numel( children ) 
            if strcmp( children(idx).getId(), id ) 
               mcosHandle = children(idx);
               break;
            end
        end
    end

  end

end
