function renderMenus(this)

% Copyright 2017 The MathWorks, Inc.

% Do not associate callbacks with menus
% These get sync'd to the buttons, which have the callbacks

% Pan/zoom group plug-in
this.ZoomInMenu = spcwidgets.ToggleMenu( ...
    this.Application.Handles.toolsMenu, ...
    'Tag', 'uimgr.spctogglemenu_ZoomIn', ...
    'Label', getString(message('images:commonUIString:zoomInMenubarLabel')), ...
    'Callback', @(hcbo,ev) toggle(this, 'ZoomIn'), ...
    'Enable', this.ZoomInButton.Enable, ...
    'Checked', this.ZoomInButton.State, ...
    'Separator','on');

this.ZoomOutMenu = spcwidgets.ToggleMenu( ...
    this.Application.Handles.toolsMenu, ...
    'Tag', 'uimgr.spctogglemenu_ZoomOut', ...
    'Label', getString(message('images:commonUIString:zoomOutMenubarLabel')), ...
    'Callback', @(hcbo,ev) toggle(this, 'ZoomOut'), ...
    'Enable', this.ZoomOutButton.Enable, ...
    'Checked', this.ZoomOutButton.State);

this.PanMenu = spcwidgets.ToggleMenu( ...
    this.Application.Handles.toolsMenu, ...
    'Tag', 'uimgr.spctogglemenu_Pan', ...
    'Label', getString(message('images:commonUIString:panMenubarLabel')), ...
    'Callback', @(hcbo,ev) toggle(this, 'Pan'), ...
    'Enable', this.PanButton.Enable, ...
    'Checked', this.PanButton.State);

this.MaintainMenu = spcwidgets.ToggleMenu( ...
    this.Application.Handles.toolsMenu, ...
    'Tag', 'uimgr.spctogglemenu_Maintain', ...
    'Label', getString(message('images:implayUIString:maintainFitMenuLabel')), ...
    'Callback', @(hcbo,ev) toggle(this, 'FitToView'), ...
    'Enable', this.MaintainButton.Enable, ...
    'Checked', this.MaintainButton.State, ...
    'Separator','on');

% -------------------------------------------------------------------------
function toggle(this, mode)

% If we are toggling the current mode, then turn it off.  Otherwise, set
% the current mode to what we are toggling.
if strcmpi(mode, this.Mode)
    this.Mode = 'off';
else
    this.Mode = mode;
end
