function renderToolbars(this)

% Copyright 2017 The MathWorks, Inc.

% Group of Pan/Zoom
this.ZoomInButton = uitoggletool( ...
    this.Application.Handles.mainToolbar, ...
    'Tag', 'uimgr.uitoggletool_ZoomIn', ...
    'Tooltip', getString(message('images:commonUIString:zoomInTooltip')), ...
    'BusyAction', 'cancel', ...
    'Interruptible', 'off', ...
    'Click', @(hco,ev) toggle(this, 'ZoomIn'), ...
    'CData', this.Application.getIcon('toggle_zoom_in'), ...
    'Separator','on');

this.ZoomOutButton = uitoggletool( ...
    this.Application.Handles.mainToolbar, ...
    'Tag', 'uimgr.uitoggletool_ZoomOut', ...
    'Tooltip', getString(message('images:commonUIString:zoomOutTooltip')), ...
    'BusyAction', 'cancel', ...
    'Interruptible', 'off', ...
    'Click', @(hco,ev) toggle(this, 'ZoomOut'), ...
    'CData', this.Application.getIcon('toggle_zoom_out'));

this.PanButton = uitoggletool( ...
    this.Application.Handles.mainToolbar, ...
    'Tag', 'uimgr.uitoggletool_Pan', ...
    'Tooltip', getString(message('images:implayUIString:panTooltip')), ...
    'Click', @(hco,ev) toggle(this, 'Pan'), ...
    'CData', this.Application.getIcon('toggle_pan'));

this.MaintainButton = uitoggletool( ...
    this.Application.Handles.mainToolbar, ...
    'Tag', 'uimgr.uitoggletool_Maintain', ...
    'Tooltip', getString(message('images:implayUIString:maintainFitTooltip')), ...
    'BusyAction', 'cancel', ...
    'Interruptible', 'off', ...
    'Click', @(hco,ev) toggle(this, 'FitToView'), ...
    'CData', this.Application.getIcon('fit_to_view'), ...
    'Separator','on');

this.MagCombobox = spcwidgets.MagCombobox( ...
    this.Application.Handles.mainToolbar, ...
    'Tag', 'uimgr.spcmagcombobox_MagCombo', ...
    'SelectedItem', sprintf('%d%%', round(100*getPropertyValue(this, 'Magnification'))));

% -------------------------------------------------------------------------
function toggle(this, mode)

% If we are toggling the current mode, then turn it off.  Otherwise, set
% the current mode to what we are toggling.
if strcmpi(mode, this.Mode)
    this.Mode = 'off';
else
    this.Mode = mode;
end
