function varargout = mex_legacy(varargin)

% Copyright 1984-2013 The MathWorks, Inc.
% This is an autogenerated file.  Do not modify.

try
    [varargout{1:nargout}]=mex_helper(varargin{:});
catch exception
    throw(exception);
end
