function prefspanel
%PREFSPANEL Registers a serial port object preferences control panel.
%
%   PREFSPANEL registers a Preferences Control panel for the serial port
%   object with the MATLAB IDE.
%

%   Copyright 1999-2013 The MathWorks, Inc.

% Register Object-based context menus items in the Workspace Browser.

% Define Serial Port Context menu (note that Instrument Control Toolbox
% redefines this in toolbox\instrument\instrument\prefspanel.m
contextMenuCallbackCategory = getString(message('MATLAB:serial:prefspanel:contextMenuCallbackCategory'));
displaySummaryMenuItem = getString(message('MATLAB:serial:prefspanel:displaySummaryMenuItem'));
propertyInspectorMenuItem = getString(message('MATLAB:serial:prefspanel:propertyInspectorMenuItem'));
serialHelpMenuItem = getString(message('MATLAB:serial:prefspanel:serialHelpMenuItem'));

com.mathworks.mlwidgets.workspace.MatlabCustomClassRegistry.registerClassCallbacks(...
    {'serial'},...
    contextMenuCallbackCategory,...
    {displaySummaryMenuItem, ...
	propertyInspectorMenuItem,...
	'-',...
	serialHelpMenuItem},...
    {'display($1)', ...
	'inspect($1);', ...
	'',...
	'help serial/Contents.m'});
