classdef UIComponentsInspectorRegistrator < internal.matlab.inspector.peer.InspectorRegistrator
    % Registers component property inspector views
    %
    % This will be called during the property inspector build process
    
    % Copyright 2016 The MathWorks, Inc.
    
    methods
        function registerInspectorComponents(obj)
            
            tempFigure = uifigure('Visible', 'off');
            
            % List of Applications to register with.  Only register
            % AppDesigner for now, so components like figure aren't also
            % modified to use the AppDesigner specific view.
            applicationNames = {
                % App Designer
                'AppDesigner'; ...
                
                % Regular Inspector
                % 'default'; ...
                
                % Namespace used by MOTW
                % 'PropertyInspector'
                };
            
            % Components To Register
            %
            % This list should be able to be updated without needing to update any code
            % further down
            
            % Registering these components adds roughly 25-27 seconds to the
            % appdesigner load time. See geck: 1271705 for more details
            components = {
                'matlab.ui.control.Label', ...
                'matlab.ui.control.TextArea', ...
                'matlab.ui.control.EditField', ...
                'matlab.ui.control.NumericEditField', ...
                'matlab.ui.control.Spinner', ...
                'matlab.ui.control.Slider', ...
                'matlab.ui.control.Button', ...
                'matlab.ui.control.StateButton', ...
                'matlab.ui.control.CheckBox', ...
                'matlab.ui.control.DropDown', ...
                'matlab.ui.control.ListBox', ...
                'matlab.ui.container.ButtonGroup', ...
                'matlab.ui.container.Panel', ...
                'matlab.ui.container.Tab', ...
                'matlab.ui.container.TabGroup', ...
                'matlab.ui.control.RadioButton', ...
                'matlab.ui.control.ToggleButton', ...
                'matlab.ui.control.Lamp', ...
                'matlab.ui.control.Gauge', ...
                'matlab.ui.control.LinearGauge', ...
                'matlab.ui.control.NinetyDegreeGauge', ...
                'matlab.ui.control.SemicircularGauge', ...
                'matlab.ui.control.Knob', ...
                'matlab.ui.control.DiscreteKnob', ...
                'matlab.ui.control.Switch', ...
                'matlab.ui.control.ToggleSwitch', ...
                'matlab.ui.control.RockerSwitch', ...
                'matlab.ui.control.UIAxes', ...
                'matlab.ui.control.Table', ...
                'matlab.ui.container.Menu', ...
                'matlab.ui.container.Tree', ...
                'matlab.ui.container.TreeNode', ...
                'matlab.ui.Figure', ...
                };
            
            % Loop over all components
            for componentIdx = 1:length(components)
                
                componentFullName = components{componentIdx};
                indices = regexp(componentFullName, '\.');
                componentShortName = componentFullName(indices(end) + 1 : end);
                
                % Assume its inspector.internal.<ShortName>PropertyView
                %
                % Ex: inspector.internal.LabelPropertyView
                propertyViewClass = sprintf('inspector.internal.%sPropertyView', componentShortName);
                
                parent = [];
                if(strcmp(componentFullName, 'matlab.ui.Figure'))
                    defaultObj = tempFigure;
                    
                elseif(strcmp(componentFullName, 'matlab.ui.container.Tab'))
                    parent = matlab.ui.container.TabGroup;
                    defaultObj = feval(componentFullName, 'Parent', parent );
                    
                elseif(strcmp(componentFullName, 'matlab.ui.control.RadioButton'))
                    parent = matlab.ui.container.ButtonGroup;
                    defaultObj = feval(componentFullName, 'Parent', parent);
                    
                elseif(strcmp(componentFullName, 'matlab.ui.control.ToggleButton'))
                    parent = matlab.ui.container.ButtonGroup;
                    defaultObj = feval(componentFullName, 'Parent', parent);
                    
                elseif(strcmp(componentFullName, 'matlab.ui.container.TreeNode'))
                    parent = matlab.ui.container.Tree;
                    defaultObj = feval(componentFullName, 'Parent', parent);
                    
                else
                    defaultObj = feval(componentFullName, 'Parent', tempFigure);
                end
                
                % Loop over all applications
                for applicationIdx = 1:length(applicationNames)
                    
                    applicationName = applicationNames{applicationIdx};
                    
                    
                    % Register
                    internal.matlab.inspector.peer.InspectorFactory.registerInspectorView(...
                        componentFullName, ...
                        applicationName, ...
                        propertyViewClass, ...
                        defaultObj ...
                        );
                end                
                delete(parent)   
            end            
            delete(tempFigure);
        end
    end
end
