function autoscaleSimDerivedMinMaxView = getAutoscalingView(this)

% Copyright 2014 The MathWorks, Inc.

autoscaleSimDerivedMinMaxProps = [DAStudio.MEViewProperty('Run'),...
                    DAStudio.MEViewProperty('CompiledDT'),DAStudio.MEViewProperty('Accept'),...
                    DAStudio.MEViewProperty('ProposedDT'),DAStudio.MEViewProperty('SpecifiedDT'),...
                    DAStudio.MEViewProperty('CompiledDesignMin'),DAStudio.MEViewProperty('CompiledDesignMax'),...
                    DAStudio.MEViewProperty('DerivedMin'),DAStudio.MEViewProperty('DerivedMax'),...
                    DAStudio.MEViewProperty('SimMin'),DAStudio.MEViewProperty('SimMax'),...
                    DAStudio.MEViewProperty('DesignMin'),DAStudio.MEViewProperty('DesignMax'),...
    DAStudio.MEViewProperty('ProposedMin'),DAStudio.MEViewProperty('ProposedMax'),...
    DAStudio.MEViewProperty('OverflowWrap'), DAStudio.MEViewProperty('OverflowSaturation')];
autoscaleSimDerivedMinMaxView = DAStudio.MEView(fxptui.message('labelViewAutoscaling'),...
                                                fxptui.message('descViewAutoscaling'));
autoscaleSimDerivedMinMaxView.Properties = autoscaleSimDerivedMinMaxProps;
autoscaleSimDerivedMinMaxView.SortName = 'Name';
autoscaleSimDerivedMinMaxView.SortOrder = 'Asc';
autoscaleSimDerivedMinMaxView.IsFactoryView = true;
this.addInternalName(autoscaleSimDerivedMinMaxView);

%--------------------------------------------------------------
