function SimDerivedMinMaxView = getDataCollectionView(this)

% Copyright 2014 The MathWorks, Inc.

SimDerivedMinMaxProps = [DAStudio.MEViewProperty('Run'),...
                    DAStudio.MEViewProperty('CompiledDT'),DAStudio.MEViewProperty('SpecifiedDT'),...
                    DAStudio.MEViewProperty('CompiledDesignMin'),DAStudio.MEViewProperty('CompiledDesignMax'),...
                    DAStudio.MEViewProperty('DerivedMin'),DAStudio.MEViewProperty('DerivedMax'),...
                    DAStudio.MEViewProperty('SimMin'), DAStudio.MEViewProperty('SimMax'),...
                    DAStudio.MEViewProperty('DesignMin'),DAStudio.MEViewProperty('DesignMax'),...
                    DAStudio.MEViewProperty('OverflowWrap'), DAStudio.MEViewProperty('OverflowSaturation')];
SimDerivedMinMaxView = DAStudio.MEView(fxptui.message('labelViewDataCollection'), ...
                                       fxptui.message('descViewDataCollection'));
SimDerivedMinMaxView.Properties = SimDerivedMinMaxProps;
SimDerivedMinMaxView.SortName = 'Name';
SimDerivedMinMaxView.SortOrder = 'Asc';
SimDerivedMinMaxView.IsFactoryView = true;
this.addInternalName(SimDerivedMinMaxView);
