function initializeFactoryMap(this)
% INITIALIZEFACTORYMAP initializes the internal map with factory views

% Copyright 2014 The MathWorks, Inc.

this.FactoryMap = [{fxptui.message('labelViewDataCollection'),  @(this)getDataCollectionView(this)};...
              {fxptui.message('labelViewSimulation'),  @(this)getSimulationView(this)};...
              {fxptui.message('labelViewDerivedMinMax'), @(this)getDerivedView(this)};...
              {fxptui.message('labelViewAutoscaling'), @(this)getAutoscalingView(this)};...
              {fxptui.message('labelViewAutoscalingSimMinMax'), @(this)getAutoscalingSimView(this)};...
              {fxptui.message('labelViewAutoscalingDerivedMinMax'), @(this)getAutoscalingDerivedView(this)}];

%---------------------------------------------------
%[EOF]
