function plugins = getFactoryDefaultPlugins
% This function is undocumented.

% Copyright 2014-2017 The MathWorks, Inc.

import matlab.unittest.Verbosity;
import matlab.unittest.plugins.LoggingPlugin;
import matlab.unittest.plugins.TestRunProgressPlugin;
import matlab.unittest.plugins.FailureDiagnosticsPlugin;
import matlab.unittest.plugins.DiagnosticsRecordingPlugin;
import matlab.unittest.internal.plugins.StopOnFailuresPluginEnabler;
import matlab.unittest.internal.plugins.FailOnWarningsPluginEnabler;
import matlab.unittest.internal.services.plugins.locateAdditionalDefaultPlugins;

plugins = [ ...
    StopOnFailuresPluginEnabler,...
    FailOnWarningsPluginEnabler,...
    LoggingPlugin.withVerbosity(Verbosity.Terse), ...
    TestRunProgressPlugin.withVerbosity(Verbosity.Concise), ...
    FailureDiagnosticsPlugin, ...
    DiagnosticsRecordingPlugin, ...
    locateAdditionalDefaultPlugins( ...
        ?matlab.unittest.internal.services.plugins.TestRunnerPluginService,...
        'matlab.unittest.internal.services.plugins')];
end

% LocalWords:  plugins unittest
