function [panel, api, minSize] = createModeGroup(this, hParent)
%CREATEMODEGROUP Creates a panel for the mode selections.
%   The mode refers to "cross track inclusion mode" as well as the
%   "Geolocation mode", both of which are properties of HDF_EOS SWATH
%   files.
%
%   Function arguments
%   ------------------
%   THIS: the swathPanel object instance.
%   HPARENT: the panel which will be our HG parent.

%   Copyright 2005-2013 The MathWorks, Inc.
    
    % Create the UI components.
    prefs = this.fileTree.fileFrame.prefs;

    ctiStr = {'AnyPoint', 'MidPoint', 'EndPoint'};
    geoStr = {'Internal', 'External'};

    panel = uipanel('Parent',hParent,...
        'title', getString(message('MATLAB:imagesci:hdftool:selectionMode')),...
        'BorderType','etchedin');

    textWidth = 22;
    popWidth = 13;
    height = prefs.charBtnHeight+prefs.charPad(2);
    pos = [0 prefs.charLabelOffset+prefs.charPad(2) textWidth prefs.charTextHeight];

    uicontrol('Style','Text',...
        'Parent',panel,...
        'Units', 'Characters',...
        'Position', pos + [0 height 0 0],...
        'HorizontalAlignment','Right',...
        'String', getString(message('MATLAB:imagesci:hdftool:crossTrackInclusion')));

    uicontrol('Style','Text',...
        'Parent',panel,...
        'Units', 'Characters',...
        'Position', pos,...
        'HorizontalAlignment','Right',...
        'String',getString(message('MATLAB:imagesci:hdftool:geolocationMode')));

    pos = [textWidth+prefs.charPad(1) prefs.charPad(2) popWidth prefs.charBtnHeight];
    popupCtrl(1) = uicontrol('Style','popupmenu',...
        'Parent',panel,...
        'Units', 'Characters',...
        'Position', pos + [0 height 0 0],...
        'BackgroundColor',prefs.colorPrefs.backgroundColor, ...
        'ForegroundColor',prefs.colorPrefs.textColor, ...
        'HorizontalAlignment','Left',...
        'String',ctiStr,...
        'Tag', 'crossTrackInclusion',...
        'Callback', @(varargin)(this.buildImportCommand(false)) );

    popupCtrl(2) = uicontrol('Style','popupmenu',...
        'Parent',panel,...
        'Units', 'Characters',...
        'Position', pos,...
        'HorizontalAlignment','Left',...
        'String',geoStr,...
        'Tag', 'geolocationMode',...
        'Callback', @(varargin)(this.buildImportCommand(false)) );

    minSize = [pos(1)+pos(3)+prefs.charPad(1) 2*(height+prefs.charPad(2))].*prefs.charExtent;

    set(panel,'WidthLimits',[minSize(1) minSize(1)],...
        'HeightLimits',[minSize(2) minSize(2)] );

    % Create the API.
    api.getCTInclusionMode = @getCTInclusionMode;
    api.getGeolocationMode = @getGeolocationMode;
    api.reset              = @reset;

    %===========================================================
    function out = getCTInclusionMode()
        ind = get(popupCtrl(1),'Value');
        out = ctiStr{ind};
    end

    %===========================================================
    function out = getGeolocationMode()
        ind = get(popupCtrl(2),'Value');
        out = geoStr{ind};
    end

    %===========================================================
    function reset()
        set(popupCtrl,'Value',1);
    end

end
