function hdlfm = hdlfimath
% Return fimath settings suitable for HDL code generation.

% Use sum and product FullPrecision option for better HDL code generation
hdlfm = fimath(...
    'RoundingMethod',       'Floor', ...
    'OverflowAction',       'Wrap',  ...
    'ProductMode',          'FullPrecision', ...
    'SumMode',              'FullPrecision');

%   Copyright 2007-2012 The MathWorks, Inc.
