function tocfifunctions
% Functions that work with fi objects.
% -----------------------------------------
%
%   <a href="matlab:help embedded.fi.abs                   ">abs</a>                   - Absolute value.
%   <a href="matlab:help accumneg                          ">accumneg</a>              - Subtract two fi objects with pre-cast.
%   <a href="matlab:help accumpos                          ">accumpos</a>              - Add two fi objects with pre-cast.
%   <a href="matlab:help all                               ">all</a>                   - True if all elements of a vector are nonzero.
%   <a href="matlab:help and                               ">and</a>                   - Logical AND: called for A & B.
%   <a href="matlab:help any                               ">any</a>                   - True if any element of a vector is nonzero.
%   <a href="matlab:help area                              ">area</a>                  - Create filled area 2-D plot.
%   <a href="matlab:help atan2                             ">atan2</a>                 - Four quadrant inverse tangent.
%   <a href="matlab:help bar                               ">bar</a>                   - Create vertical bar graph.
%   <a href="matlab:help barh                              ">barh</a>                  - Create horizontal bar graph.
%   <a href="matlab:help embedded.fi.bin                   ">bin</a>                   - Binary representation.
%   <a href="matlab:help embedded.fi.bitand                ">bitand</a>                - Bit-wise AND.
%   <a href="matlab:help embedded.fi.bitandreduce          ">bitandreduce</a>          - Bit-wise AND on a range of bits.
%   <a href="matlab:help embedded.fi.bitcmp                ">bitcmp</a>                - Complement bits.
%   <a href="matlab:help embedded.fi.bitconcat             ">bitconcat</a>             - Combine stored integer bits of fixed point words.
%   <a href="matlab:help embedded.fi.bitget                ">bitget</a>                - Get bit.
%   <a href="matlab:help embedded.fi.bitor                 ">bitor</a>                 - Bit-wise OR.
%   <a href="matlab:help embedded.fi.bitorreduce           ">bitorreduce</a>           - Bit-wise OR on a range of bits.
%   <a href="matlab:help embedded.fi.bitreplicate          ">bitreplicate</a>          - Combine stored integer bits of a fixed point word N times.
%   <a href="matlab:help embedded.fi.bitrol                ">bitrol</a>                - Rotate left on stored integer bits.
%   <a href="matlab:help embedded.fi.bitror                ">bitror</a>                - Rotate right on stored integer bits.
%   <a href="matlab:help embedded.fi.bitset                ">bitset</a>                - Set bit.
%   <a href="matlab:help embedded.fi.bitshift              ">bitshift</a>              - Bit-wise shift.
%   <a href="matlab:help embedded.fi.bitsliceget           ">bitsliceget</a>           - Get a consecutive set of bits.
%   <a href="matlab:help embedded.fi.bitsll                ">bitsll</a>                - Bit shift left logical.
%   <a href="matlab:help embedded.fi.bitsra                ">bitsra</a>                - Bit shift right arithmetic.
%   <a href="matlab:help embedded.fi.bitsrl                ">bitsrl</a>                - Bit shift right logical.
%   <a href="matlab:help embedded.fi.bitxor                ">bitxor</a>                - Bit-wise XOR.
%   <a href="matlab:help embedded.fi.bitxorreduce          ">bitxorreduce</a>          - Bit-wise XOR on a range of bits.
%   <a href="matlab:help embedded.fi.buffer                ">buffer</a>                - Buffer a vector into a matrix of data frames.
%   <a href="matlab:help embedded.fi.ceil                  ">ceil</a>                  - Round towards positive infinity.
%   <a href="matlab:help clabel                            ">clabel</a>                - Create contour plot elevation labels.
%   <a href="matlab:help comet                             ">comet</a>                 - Create 2-D comet plot.
%   <a href="matlab:help comet3                            ">comet3</a>                - Create 3-D comet plot.
%   <a href="matlab:help compass                           ">compass</a>               - Plot arrows emanating from origin.
%   <a href="matlab:help embedded.fi.complex               ">complex</a>               - Construct complex result from real and imaginary parts.
%   <a href="matlab:help coneplot                          ">coneplot</a>              - Plot velocity vectors as cones in 3-D vector field.
%   <a href="matlab:help embedded.fi.conj                  ">conj</a>                  - Complex conjugate.
%   <a href="matlab:help contour                           ">contour</a>               - Create contour graph of matrix.
%   <a href="matlab:help contour3                          ">contour3</a>              - Create 3-D contour plot.
%   <a href="matlab:help contourc                          ">contourc</a>              - Create two-level contour plot.
%   <a href="matlab:help contourf                          ">contourf</a>              - Create filled 2-D contour plot.
%   <a href="matlab:help embedded.fi.conv                  ">conv</a>                  - Convolution.
%   <a href="matlab:help embedded.fi.convergent            ">convergent </a>           - Round to nearest integer; ties round to nearest even integer.
%   <a href="matlab:help cordicabs                         ">cordicabs</a>             - CORDIC-based approximation of complex magnitude (absolute value).
%   <a href="matlab:help cordicangle                       ">cordicangle</a>           - CORDIC-based approximation of complex phase angle.
%   <a href="matlab:help cordicatan2                       ">cordicatan2</a>           - CORDIC-based approximation of four quadrant inverse tangent (atan2).
%   <a href="matlab:help cordiccart2pol                    ">cordiccart2pol</a>        - CORDIC-based approximation of Cartesian to polar conversion.
%   <a href="matlab:help cordiccexp                        ">cordiccexp</a>            - CORDIC-based approximation of complex exponential e^(j*THETA).
%   <a href="matlab:help cordiccos                         ">cordiccos</a>             - CORDIC-based approximation of cosine.
%   <a href="matlab:help cordicpol2cart                    ">cordicpol2cart</a>        - CORDIC-based approximation of polar to Cartesian conversion.
%   <a href="matlab:help cordicrotate                      ">cordicrotate</a>          - CORDIC-based approximation of complex rotation.
%   <a href="matlab:help cordicsincos                      ">cordicsincos</a>          - CORDIC-based approximation of sine and cosine.
%   <a href="matlab:help cordicsin                         ">cordicsin</a>             - CORDIC-based approximation of sine.
%   <a href="matlab:help cos                               ">cos</a>                   - Cosine function.
%   <a href="matlab:help embedded.fi.ctranspose            ">ctranspose</a>            - Complex conjugate transpose: called for A'
%   <a href="matlab:help embedded.fi.dec                   ">dec</a>                   - Decimal integer string representation of stored integer.
%   <a href="matlab:help diag                              ">diag</a>                  - Diagonal matrices or diagonals of matrix.
%   <a href="matlab:help disp                              ">disp</a>                  - Display without printing the variable name.
%   <a href="matlab:help embedded.fi.double                ">double</a>                - Closest real-world-value that can be represented as a double.
%   <a href="matlab:help end                               ">end</a>                   - Last index of array.
%   <a href="matlab:help embedded.fi.eps                   ">eps</a>                   - Scaling of the least-significant bit.
%   <a href="matlab:help embedded.fi.eq                    ">eq</a>                    - Equal: called for A==B.
%   <a href="matlab:help errorbar                          ">errorbar</a>              - Plot error bars along curve.
%   <a href="matlab:help etreeplot                         ">etreeplot</a>             - Plot elimination tree.
%   <a href="matlab:help ezcontour                         ">ezcontour</a>             - Easy-to-use contour plotter.
%   <a href="matlab:help ezcontourf                        ">ezcontourf</a>            - Easy-to-use filled contour plotter.
%   <a href="matlab:help ezmesh                            ">ezmesh</a>                - Easy-to-use 3-D mesh plotter.
%   <a href="matlab:help ezplot                            ">ezplot</a>                - Easy-to-use function plotter.
%   <a href="matlab:help ezplot3                           ">ezplot3</a>               - Easy-to-use 3-D parametric curve plotter.
%   <a href="matlab:help ezpolar                           ">ezpolar</a>               - Easy-to-use polar coordinate plotter.
%   <a href="matlab:help ezsurf                            ">ezsurf</a>                - Easy-to-use 3-D colored surface plotter.
%   <a href="matlab:help ezsurfc                           ">ezsurfc</a>               - Easy-to-use combination surface/contour plotter.
%   <a href="matlab:help feather                           ">feather</a>               - Plot velocity vectors.
%   <a href="matlab:help fi                                ">fi</a>                    - Constructs a fi object.
%   <a href="matlab:help embedded.fi.filter                ">filter</a>                - One-dimensional digital filter.
%   <a href="matlab:help embedded.fi.fimath                ">fimath</a>                - Get fimath object associated with this fi.
%   <a href="matlab:help embedded.fi.fix                   ">fix</a>                   - Round towards zero.
%   <a href="matlab:help embedded.fi.fixed.aggregateType   ">fixed.aggregateType</a>   - Compute aggregate numerictype.
%   <a href="matlab:help embedded.fi.floor                 ">floor</a>                 - Round towards negative infinity.
%   <a href="matlab:help fplot                             ">fplot</a>                 - Plot function between specified limits.
%   <a href="matlab:help embedded.fi.ge                    ">ge</a>                    - Greater than or equal: called for A >= B.
%   <a href="matlab:help embedded.fi.getlsb                ">getlsb</a>                - Get value of Least Significant Bit (LSB).
%   <a href="matlab:help embedded.fi.getmsb                ">getmsb</a>                - Get value of Most Significant Bit (MSB).
%   <a href="matlab:help gplot                             ">gplot</a>                 - Plot set of nodes using adjacency matrix.
%   <a href="matlab:help embedded.fi.gt                    ">gt</a>                    - Greater than: called for A > B.
%   <a href="matlab:help hankel                            ">hankel</a>                - Hankel matrix.
%   <a href="matlab:help embedded.fi.hex                   ">hex</a>                   - Hex representation of the stored integer.
%   <a href="matlab:help hist                              ">hist</a>                  - Create histogram plot.
%   <a href="matlab:help histc                             ">histc</a>                 - Histogram count.
%   <a href="matlab:help embedded.fi.horzcat               ">horzcat</a>               - Horizontal concatenation: called for [A B].
%   <a href="matlab:help imag                              ">imag</a>                  - Complex imaginary part.
%   <a href="matlab:help embedded.fi.storedInteger         ">storedInteger</a>         - Stored integer value as MATLAB native integer.
%   <a href="matlab:help embedded.fi.storedIntegerToDouble ">storedIntegerToDouble</a> - Convert the stored integer value to built-in double.
%   <a href="matlab:help embedded.fi.int16                 ">int16</a>                 - Convert fi object to int16.
%   <a href="matlab:help embedded.fi.int32                 ">int32</a>                 - Convert fi object to int32.
%   <a href="matlab:help embedded.fi.int64                 ">int64</a>                 - Convert fi object to int64.
%   <a href="matlab:help embedded.fi.int8                  ">int8</a>                  - Convert fi object to int8.
%   <a href="matlab:help embedded.fi.intmax                ">intmax</a>                - Largest stored integer value.
%   <a href="matlab:help embedded.fi.intmin                ">intmin</a>                - Smallest stored integer value.
%   <a href="matlab:help embedded.fi.isboolean             ">isboolean</a>             - True if fi DataType property is 'boolean'.
%   <a href="matlab:help embedded.fi.iscolumn              ">iscolumn</a>              - True if array is a column vector.
%   <a href="matlab:help embedded.fi.isdouble              ">isdouble</a>              - True if fi DataType property is 'double'.
%   <a href="matlab:help isempty                           ">isempty</a>               - True if empty.
%   <a href="matlab:help embedded.fi.isequal               ">isequal</a>               - True arrays are numerically equal.
%   <a href="matlab:help embedded.fi.isfi                  ">isfi</a>                  - True if fi object.
%   <a href="matlab:help embedded.fi.isfimathlocal         ">isfimathlocal</a>         - True if fi has a local fimath object.
%   <a href="matlab:help isfinite                          ">isfinite</a>              - True for finite elements.
%   <a href="matlab:help embedded.fi.isfixed               ">isfixed</a>               - True if fi DataType property is 'Fixed'.
%   <a href="matlab:help embedded.fi.isfloat               ">isfloat</a>               - True if fi DataType property is 'double' or 'single'.
%   <a href="matlab:help isinf                             ">isinf</a>                 - True for infinite elements.
%   <a href="matlab:help isnan                             ">isnan</a>                 - True for Not-a-Number elements.
%   <a href="matlab:help embedded.fi.isnumeric             ">isnumeric</a>             - True for numeric arrays.  fi objects are considered numeric arrays.
%   <a href="matlab:help embedded.fi.ispropequal           ">ispropequal</a>           - True if arrays are numerically equal and all properties are equal.
%   <a href="matlab:help isreal                            ">isreal</a>                - True if array does not have an imaginary part.
%   <a href="matlab:help embedded.fi.isrow                 ">isrow</a>                 - True if array is a row vector.
%   <a href="matlab:help isscalar                          ">isscalar</a>              - True if array is a scalar.
%   <a href="matlab:help embedded.fi.isscaleddouble        ">isscaleddouble</a>        - True if fi DataType property is 'ScaledDouble'.
%   <a href="matlab:help embedded.fi.isscaledtype          ">isscaledtype</a>          - True if fi DataType property is 'Fixed' or 'ScaledDouble'.
%   <a href="matlab:help embedded.fi.isscalingbinarypoint  ">isscalingbinarypoint</a>  - True if fi object has binary point scaling or trivial slope and bias scaling.
%   <a href="matlab:help embedded.fi.isscalingslopebias    ">isscalingslopebias</a>    - True if fi object has nontrivial slope and bias scaling.
%   <a href="matlab:help embedded.fi.isscalingunspecified  ">isscalingunspecified</a>  - True if fi object is fixed-point or scaled double and its scaling has not been specified.
%   <a href="matlab:help embedded.fi.issigned              ">issigned</a>              - True if the Signed property is true.
%   <a href="matlab:help embedded.fi.issingle              ">issingle</a>              - True if fi DataType property is 'single'.
%   <a href="matlab:help embedded.fi.issparse              ">issparse</a>              - True for sparse matrix.
%   <a href="matlab:help isvector                          ">isvector</a>              - True if array is a vector (either row or column).
%   <a href="matlab:help embedded.fi.le                    ">le</a>                    - Less than or equal: called for A <= B.
%   <a href="matlab:help length                            ">length</a>                - Length of vector, or max dimension.
%   <a href="matlab:help line                              ">line</a>                  - Create line object.
%   <a href="matlab:help logical                           ">logical</a>               - Convert numeric values to logical.
%   <a href="matlab:help loglog                            ">loglog</a>                - Log-log scale plot.
%   <a href="matlab:help embedded.fi.logreport             ">logreport</a>             - Quantization report.
%   <a href="matlab:help embedded.fi.lowerbound            ">lowerbound</a>            - Least value representable.
%   <a href="matlab:help embedded.fi.lsb                   ">lsb</a>                   - Scale of the least-significant-bit.
%   <a href="matlab:help embedded.fi.lt                    ">lt</a>                    - Less than: called for A < B.
%   <a href="matlab:help embedded.fi.max                   ">max</a>                   - Largest component.
%   <a href="matlab:help embedded.fi.maxlog                ">maxlog</a>                - Largest real-world value of fi object logged.
%   <a href="matlab:help embedded.fi.mean                  ">mean</a>                  - Average or mean value of fixed-point array.
%   <a href="matlab:help embedded.fi.median                ">median</a>                - Median value of fixed-point array.
%   <a href="matlab:help mesh                              ">mesh</a>                  - Create mesh plot.
%   <a href="matlab:help meshc                             ">meshc</a>                 - Create mesh plot with contour plot.
%   <a href="matlab:help meshz                             ">meshz</a>                 - Create mesh plot with curtain plot.
%   <a href="matlab:help embedded.fi.min                   ">min</a>                   - Smallest component.
%   <a href="matlab:help embedded.fi.minlog                ">minlog</a>                - Smallest real-world value of fi object logged.
%   <a href="matlab:help embedded.fi.minus                 ">minus</a>                 - Minus: called for A - B.
%   <a href="matlab:help embedded.fi.mod                   ">mod</a>                   - Modulus after division.
%   <a href="matlab:help embedded.fi.mpower                ">mpower</a>                - Matrix power: A^K.
%   <a href="matlab:help embedded.fi.mrdivide              ">mrdivide</a>              - Slash (/),  or right matrix divide.
%   <a href="matlab:help embedded.fi.mtimes                ">mtimes</a>                - Matrix multiply: called for A * B.
%   <a href="matlab:help ndgrid                            ">ndgrid</a>                - Generate arrays for N-D functions and interpolation.
%   <a href="matlab:help ndims                             ">ndims</a>                 - Number of dimensions.
%   <a href="matlab:help embedded.fi.ne                    ">ne</a>                    - Not equal: called for A ~= B.
%   <a href="matlab:help embedded.fi.nearest               ">nearest</a>               - Round to nearest integer; ties round towards positive infinity.
%   <a href="matlab:help not                               ">not</a>                   - Logical NOT: called for ~A.
%   <a href="matlab:help embedded.fi.noverflows            ">noverflows</a>            - Number of overflows.
%   <a href="matlab:help embedded.fi.num2sdec              ">num2sdec</a>              - Convert stored integers of array of fi objects to signed decimal representation.
%   <a href="matlab:help embedded.fi.numberofelements      ">numberofelements</a>      - Number of elements in array.
%   <a href="matlab:help embedded.fi.numerictype           ">numerictype</a>           - Get numerictype object associated with this fi.
%   <a href="matlab:help embedded.fi.nunderflows           ">nunderflows</a>           - Number of underflows.
%   <a href="matlab:help embedded.fi.oct                   ">oct</a>                   - Octal representation of the stored integer.
%   <a href="matlab:help or                                ">or</a>                    - Logical OR: called for A | B.
%   <a href="matlab:help patch                             ">patch</a>                 - Create patch graphics object.
%   <a href="matlab:help pcolor                            ">pcolor</a>                - Create pseudocolor plot.
%   <a href="matlab:help permute                           ">permute</a>               - Permute array dimensions.
%   <a href="matlab:help plot                              ">plot</a>                  - Linear plot.
%   <a href="matlab:help plot3                             ">plot3</a>                 - Create 3-D line plot.
%   <a href="matlab:help plotmatrix                        ">plotmatrix</a>            - Draw scatter plots.
%   <a href="matlab:help plotyy                            ">plotyy</a>                - Create graph with y-axes on right and left sides.
%   <a href="matlab:help embedded.fi.plus                  ">plus</a>                  - Plus: called for A + B.
%   <a href="matlab:help polar                             ">polar</a>                 - Plot polar coordinates.
%   <a href="matlab:help embedded.fi.pow2                  ">pow2</a>                  - Multiply by an integral power of 2.
%   <a href="matlab:help embedded.fi.power                 ">power</a>                 - Array power: A .^ K.
%   <a href="matlab:help embedded.fi.qr                    ">qr</a>                    - Orthogonal triangular decomposition.
%   <a href="matlab:help embedded.fi.quantizer             ">quantizer</a>             - Assignment quantizer.
%   <a href="matlab:help quiver                            ">quiver</a>                - Create quiver or velocity plot.
%   <a href="matlab:help quiver3                           ">quiver3</a>               - Create 3-D quiver or velocity plot.
%   <a href="matlab:help embedded.fi.range                 ">range</a>                 - Numerical range.
%   <a href="matlab:help real                              ">real</a>                  - Complex real part.
%   <a href="matlab:help embedded.fi.realmax               ">realmax</a>               - Greatest representable value.
%   <a href="matlab:help embedded.fi.realmin               ">realmin</a>               - Smallest positive value representable.
%   <a href="matlab:help embedded.fi.removefimath          ">removefimath</a>          - Remove FIMATH object from output.
%   <a href="matlab:help repmat                            ">repmat</a>                - Replicate and tile array.
%   <a href="matlab:help embedded.fi.resetlog              ">resetlog</a>              - Clear log for fi object.
%   <a href="matlab:help rgbplot                           ">rgbplot</a>               - Plot colormap.
%   <a href="matlab:help rose                              ">rose</a>                  - Create angle histogram.
%   <a href="matlab:help embedded.fi.rdivide               ">rdivide</a>               - Right array divide (./)
%   <a href="matlab:help embedded.fi.realmax               ">realmax</a>               - Largest positive fixed-point value.
%   <a href="matlab:help embedded.fi.reinterpretcast       ">reinterpretcast</a>       - Convert fixed-point or integer data types without changing underlying data.
%   <a href="matlab:help embedded.fi.rescale               ">rescale</a>               - Change the scaling of a fi, while keeping its stored integer value.
%   <a href="matlab:help embedded.fi.resetlogging          ">resetlogging</a>          - Clear log for fi object.
%   <a href="matlab:help reshape                           ">reshape</a>               - Change shape of an array.
%   <a href="matlab:help ribbon                            ">ribbon</a>                - Create stream ribbon plot.
%   <a href="matlab:help embedded.fi.round                 ">round</a>                 - Round towards nearest integer; ties round away from zero.
%   <a href="matlab:help scatter                           ">scatter</a>               - Create scatter or bubble plot.
%   <a href="matlab:help scatter3                          ">scatter3</a>              - Create 3-D scatter or bubble plot.
%   <a href="matlab:help embedded.fi.sdec                  ">sdec</a>                  - Signed decimal representation of stored integer of fi object.
%   <a href="matlab:help embedded.fi.semilogx              ">semilogx</a>              - Semi-log scale plot.
%   <a href="matlab:help embedded.fi.semilogy              ">semilogy</a>              - Semi-log scale plot.
%   <a href="matlab:help embedded.fi.setfimath             ">setfimath</a>             - Attach fimath object to output.
%   <a href="matlab:help sfi                               ">sfi</a>                   - Signed fixed-point numeric object.
%   <a href="matlab:help embedded.fi.shiftdata             ">shiftdata</a>             - Shift data to operate on a specified dimension.
%   <a href="matlab:help embedded.fi.sign                  ">sign</a>                  - Signum function.
%   <a href="matlab:help sin                               ">sin</a>                   - Sine function.
%   <a href="matlab:help embedded.fi.single                ">single</a>                - Single-precision floating-point real-world value.
%   <a href="matlab:help size                              ">size</a>                  - Size of array.
%   <a href="matlab:help slice                             ">slice</a>                 - Draw streamlines in slice planes.
%   <a href="matlab:help embedded.fi.sort                  ">sort</a>                  - Sort elements of real-valued fi objects.
%   <a href="matlab:help spy                               ">spy</a>                   - Visualize sparsity pattern.
%   <a href="matlab:help embedded.fi.sqrt                  ">sqrt</a>                  - Square root.
%   <a href="matlab:help squeeze                           ">squeeze</a>               - Remove singleton dimensions.
%   <a href="matlab:help stairs                            ">stairs</a>                - Create stairstep graph.
%   <a href="matlab:help stem                              ">stem</a>                  - Plot discrete sequence data.
%   <a href="matlab:help stem3                             ">stem3</a>                 - Plot 3-D discrete sequence data.
%   <a href="matlab:help streamribbon                      ">streamribbon</a>          - Create 3-D stream ribbon plot.
%   <a href="matlab:help streamslice                       ">streamslice</a>           - Draw streamlines in slice planes.
%   <a href="matlab:help streamtube                        ">streamtube</a>            - Create 3-D stream tube plot.
%   <a href="matlab:help embedded.fi.stripscaling          ">stripscaling</a>          - Strip scaling information from fi.
%   <a href="matlab:help embedded.fi.subsasgn              ">subsasgn</a>              - Subscripted assignment: called for A(k) = B.
%   <a href="matlab:help subsref                           ">subsref</a>               - Subscripted reference: called for A = B(k).
%   <a href="matlab:help embedded.fi.sum                   ">sum</a>                   - Sum of elements.
%   <a href="matlab:help surf                              ">surf</a>                  - Create 3-D shaded surface plot.
%   <a href="matlab:help surfc                             ">surfc</a>                 - Create 3-D shaded surface plot with contour plot.
%   <a href="matlab:help surfl                             ">surfl</a>                 - Create surface plot with colormap-based lighting.
%   <a href="matlab:help surfnorm                          ">surfnorm</a>              - Compute and display 3-D surface normals.
%   <a href="matlab:help embedded.fi.times                 ">times</a>                 - Array multiply: called for A .* B
%   <a href="matlab:help embedded.fi.todouble              ">todouble</a>              - Convert to double precision.
%   <a href="matlab:help embedded.fi.todoublecell          ">todoublecell</a>          - Convert fi objects to cell array of doubles.
%   <a href="matlab:help embedded.fi.todoubles             ">todoubles</a>             - Convert fi objects to doubles.
%   <a href="matlab:help embedded.fi.toeplitz              ">toeplitz</a>              - Create toeplitz matrix.
%   <a href="matlab:help transpose                         ">transpose</a>             - Transpose: called for A.'
%   <a href="matlab:help treeplot                          ">treeplot</a>              - Plot picture of tree.
%   <a href="matlab:help tril                              ">tril</a>                  - Lower triangular part of matrix.
%   <a href="matlab:help trimesh                           ">trimesh</a>               - Create triangular mesh plot.
%   <a href="matlab:help triplot                           ">triplot</a>               - Create 2-D triangular plot.
%   <a href="matlab:help trisurf                           ">trisurf</a>               - Create triangular surface plot.
%   <a href="matlab:help triu                              ">triu</a>                  - Upper triangular part of matrix.
%   <a href="matlab:help ufi                               ">ufi</a>                   - Unsigned fixed-point numeric object.
%   <a href="matlab:help embedded.fi.uint16                ">uint16</a>                - Convert fi object to uint16.
%   <a href="matlab:help embedded.fi.uint32                ">uint32</a>                - Convert fi object to uint32.
%   <a href="matlab:help embedded.fi.uint64                ">uint64</a>                - Convert fi object to uint64.
%   <a href="matlab:help embedded.fi.uint8                 ">uint8</a>                 - Convert fi object to uint8.
%   <a href="matlab:help embedded.fi.uminus                ">uminus</a>                - Unary minus: called for -A
%   <a href="matlab:help embedded.fi.unshiftdata           ">unshiftdata</a>           - The inverse of shiftdata.
%   <a href="matlab:help embedded.fi.uplus                 ">uplus</a>                 - Unary plus: called for +A.
%   <a href="matlab:help embedded.fi.upperbound            ">upperbound</a>            - Greatest representable value.
%   <a href="matlab:help embedded.fi.vertcat               ">vertcat</a>               - Vertical concatenation: called for [A;B]
%   <a href="matlab:help voronoi                           ">voronoi</a>               - Create Voronoi diagram.
%   <a href="matlab:help voronoin                          ">voronoin</a>              - Create n-D Voronoi diagram.
%   <a href="matlab:help waterfall                         ">waterfall</a>             - Create waterfall plot.
%   <a href="matlab:help xor                               ">xor</a>                   - Logical EXCLUSIVE OR.

%   Copyright 2012 The MathWorks, Inc.
