function tableDataStruct = getTable(this, data, unit)
    % GETTABLE creates an struct data for the optimization report that
    % will be generated by the WizardController
    
    % Copyright 2017-2018 The MathWorks, Inc.
    
    tableDataStruct = this.getTableMetadata;
    % Calculating tale data memory
    tableDataMemory = numel(data.Data{end}) * data.StorageTypes(end).WordLength;
    tableDataMemory = this.convertMemoryTo(tableDataMemory, unit);
    tableDataStruct(1).TableData = tableDataMemory;
    
    isEven = isEvenSpacing(data.Spacing);
    % Calculating breakpoint memory
    for iBreakpoint = 1:data.NumberOfDimensions
        currentBreakPointMemory = (isEven*2 + ~isEven*numel(data.Data{iBreakpoint})) * data.StorageTypes(iBreakpoint).WordLength;
        currentBreakPointMemory = this.convertMemoryTo(currentBreakPointMemory, unit);
        tableDataStruct(1).BreakpointDimensions{iBreakpoint} = currentBreakPointMemory;
    end
    % Calculating total memory
    memoryUsage = data.MemoryUsage;
    memoryUsage.Unit = unit;
    tableDataStruct(1).Total = memoryUsage.Value;
end

