//>>built
require({cache:{"dojo/require":function(){define(["./_base/loader"],function(e){return{dynamic:0,normalize:function(b){return b},load:e.require}})},"dijit/main":function(){define(["dojo/_base/kernel"],function(e){return e.dijit})},"dojox/main":function(){define(["dojo/_base/kernel"],function(e){return e.dojox})},"mw-browser-utils/BrowserCheck":function(){define("dojo/_base/window dojo/window dojo/dom-construct dojo/has dojo/i18n!./l10n/nls/unsupportedErrorPage ./detect/css ./detect/object".split(" "),
function(e,b,l,c,h){var d={isBrowserValid:function(){var a=!0;c("quirks")?a=!1:c("css-enabled")?c("css-border-radius")?c("css-text-overflow")?c("object-create")||(a=!1):a=!1:a=!1:a=!1;return a},displayErrorAsOverlay:function(){l.create("div",{style:{position:"absolute",left:"0%",top:"0%","background-color":"grey","-moz-opacity":"0.7",opacity:".70",filter:"alpha(opacity\x3d70)",width:"100%",height:"100%",zIndex:"90"},id:"fadeDiv"},e.body());l.create("div",{style:{position:"relative",margin:"auto",
"margin-top":"12.35%",width:"400px",height:"300px",padding:"10px",border:"2px solid black","background-color":"#ffffff","z-index":"100","font-family":"Sans-serif"},id:"unsupportedBrowser","class":"content_module"},e.body()).innerHTML=h.unsupportedError}};return{load:function(a,b,g){d.isBrowserValid()?g():a?e.global.location=a:d.displayErrorAsOverlay()}}})},"dojo/window":function(){define("./_base/lang ./sniff ./_base/window ./dom ./dom-geometry ./dom-style ./dom-construct".split(" "),function(e,b,
l,c,h,d,a){b.add("rtl-adjust-position-for-verticalScrollBar",function(g,b){var d=l.body(b),e=a.create("div",{style:{overflow:"scroll",overflowX:"visible",direction:"rtl",visibility:"hidden",position:"absolute",left:"0",top:"0",width:"64px",height:"64px"}},d,"last"),c=a.create("div",{style:{overflow:"hidden",direction:"ltr"}},e,"last"),k=0!=h.position(c).x;e.removeChild(c);d.removeChild(e);return k});b.add("position-fixed-support",function(g,b){var d=l.body(b),e=a.create("span",{style:{visibility:"hidden",
position:"fixed",left:"1px",top:"1px"}},d,"last"),c=a.create("span",{style:{position:"fixed",left:"0",top:"0"}},e,"last"),k=h.position(c).x!=h.position(e).x;e.removeChild(c);d.removeChild(e);return k});var k={getBox:function(a){a=a||l.doc;var d="BackCompat"==a.compatMode?l.body(a):a.documentElement,e=h.docScroll(a);if(b("touch")){var c=k.get(a);a=c.innerWidth||d.clientWidth;d=c.innerHeight||d.clientHeight}else a=d.clientWidth,d=d.clientHeight;return{l:e.x,t:e.y,w:a,h:d}},get:function(a){if(b("ie")&&
k!==document.parentWindow){a.parentWindow.execScript("document._parentWindow \x3d window;","Javascript");var d=a._parentWindow;a._parentWindow=null;return d}return a.parentWindow||a.defaultView},scrollIntoView:function(a,e){try{a=c.byId(a);var k=a.ownerDocument||l.doc,r=l.body(k),n=k.documentElement||r.parentNode,u=b("ie")||b("trident"),x=b("webkit");if(!(a==r||a==n))if(!b("mozilla")&&(!u&&!x&&!b("opera")&&!b("trident")&&!b("edge"))&&"scrollIntoView"in a)a.scrollIntoView(!1);else{var B="BackCompat"==
k.compatMode,C=Math.min(r.clientWidth||n.clientWidth,n.clientWidth||r.clientWidth),y=Math.min(r.clientHeight||n.clientHeight,n.clientHeight||r.clientHeight),k=x||B?r:n,t=e||h.position(a),m=a.parentNode,x=function(a){return 6>=u||7==u&&B?!1:b("position-fixed-support")&&"fixed"==d.get(a,"position").toLowerCase()},D=this,G=function(a,d,b){"BODY"==a.tagName||"HTML"==a.tagName?D.get(a.ownerDocument).scrollBy(d,b):(d&&(a.scrollLeft+=d),b&&(a.scrollTop+=b))};if(!x(a))for(;m;){m==r&&(m=k);var f=h.position(m),
A=x(m),E="rtl"==d.getComputedStyle(m).direction.toLowerCase();if(m==k){f.w=C;f.h=y;if(k==n&&(u||b("trident"))&&E)f.x+=k.offsetWidth-f.w;f.x=0;f.y=0}else{var z=h.getPadBorderExtents(m);f.w-=z.w;f.h-=z.h;f.x+=z.l;f.y+=z.t;var s=m.clientWidth,H=f.w-s;0<s&&0<H&&(E&&b("rtl-adjust-position-for-verticalScrollBar")&&(f.x+=H),f.w=s);s=m.clientHeight;H=f.h-s;0<s&&0<H&&(f.h=s)}A&&(0>f.y&&(f.h+=f.y,f.y=0),0>f.x&&(f.w+=f.x,f.x=0),f.y+f.h>y&&(f.h=y-f.y),f.x+f.w>C&&(f.w=C-f.x));var I=t.x-f.x,J=t.y-f.y,v=I+t.w-f.w,
L=J+t.h-f.h,q,w;if(0<v*I&&(m.scrollLeft||m==k||m.scrollWidth>m.offsetHeight)){q=Math[0>I?"max":"min"](I,v);if(E&&(8==u&&!B||5<=b("trident")))q=-q;w=m.scrollLeft;G(m,q,0);q=m.scrollLeft-w;t.x-=q}if(0<L*J&&(m.scrollTop||m==k||m.scrollHeight>m.offsetHeight))q=Math.ceil(Math[0>J?"max":"min"](J,L)),w=m.scrollTop,G(m,0,q),q=m.scrollTop-w,t.y-=q;m=m!=k&&!A&&m.parentNode}}}catch(K){console.error("scrollIntoView: "+K),a.scrollIntoView(!1)}}};e.setObject("dojo.window",k);return k})},"dojo/i18n":function(){define("./_base/kernel require ./has ./_base/array ./_base/config ./_base/lang ./_base/xhr ./json module".split(" "),
function(e,b,l,c,h,d,a,k,g){l.add("dojo-preload-i18n-Api",1);var p=e.i18n={},F=/(^.*(^|\/)nls)(\/|$)([^\/]*)\/?([^\/]*)/,r=function(a,d,b,e){var c=[b+e];d=d.split("-");for(var h="",f=0;f<d.length;f++)if(h+=(h?"-":"")+d[f],!a||a[h])c.push(b+h+"/"+e),c.specificity=h;return c},n={},u=function(a,d,b){b=b?b.toLowerCase():e.locale;a=a.replace(/\./g,"/");d=d.replace(/\./g,"/");return/root/i.test(b)?a+"/nls/"+d:a+"/nls/"+b+"/"+d},x=e.getL10nName=function(a,d,b){return g.id+"!"+u(a,d,b)},B=function(a,b,e,
h,c,f){a([b],function(g){var k=d.clone(g.root||g.ROOT),m=r(!g._v1x&&g,c,e,h);a(m,function(){for(var a=1;a<m.length;a++)k=d.mixin(d.clone(k),arguments[a]);n[b+"/"+c]=k;k.$locale=m.specificity;f()})})},C=function(a){var b=h.extraLocale||[],b=d.isArray(b)?b:[b];b.push(a);return b},y=function(a,b,h){if(l("dojo-preload-i18n-Api")){var g=a.split("*"),v="preload"==g[1];v&&(n[a]||(n[a]=1,G(g[2],k.parse(g[3]),1,b)),h(1));if(!(g=v))m&&D.push([a,b,h]),g=m;if(g)return}a=F.exec(a);var p=a[1]+"/",q=a[5]||a[4],
w=p+q,g=(a=a[5]&&a[4])||e.locale||"",K=w+"/"+g;a=a?[g]:C(g);var M=a.length,r=function(){--M||h(d.delegate(n[K]))};c.forEach(a,function(a){var d=w+"/"+a;l("dojo-preload-i18n-Api")&&f(d);n[d]?r():B(b,w,p,q,a,r)})};l("dojo-preload-i18n-Api");var t=p.normalizeLocale=function(a){a=a?a.toLowerCase():e.locale;return"root"==a?"ROOT":a},m=0,D=[],G=p._preloadLocalizations=function(a,h,f,g){function k(a,d){g.isXdUrl(b.toUrl(a+".js"))||f?g([a],d):z([a],d,g)}function l(a,b){for(var d=a.split("-");d.length;){if(b(d.join("-")))return;
d.pop()}b("ROOT")}function q(){for(--m;!m&&D.length;)y.apply(null,D.shift())}function p(e){e=t(e);l(e,function(f){if(0<=c.indexOf(h,f)){var p=a.replace(/\./g,"/")+"_"+f;m++;k(p,function(a){for(var h in a){var c=a[h],k=h.match(/(.+)\/([^\/]+)$/),p;if(k&&(p=k[2],k=k[1]+"/",c._localized)){var s;if("ROOT"===f){var v=s=c._localized;delete c._localized;v.root=c;n[b.toAbsMid(h)]=v}else s=c._localized,n[b.toAbsMid(k+p+"/"+f)]=c;f!==e&&function(a,h,c,f){var k=[],p=[];l(e,function(d){f[d]&&(k.push(b.toAbsMid(a+
d+"/"+h)),p.push(b.toAbsMid(a+h+"/"+d)))});k.length?(m++,g(k,function(){for(var f=k.length-1;0<=f;f--)c=d.mixin(d.clone(c),arguments[f]),n[p[f]]=c;n[b.toAbsMid(a+h+"/"+e)]=d.clone(c);q()})):n[b.toAbsMid(a+h+"/"+e)]=c}(k,p,c,s)}}q()});return!0}return!1})}g=g||b;p();c.forEach(e.config.extraLocale,p)},f=function(){},A={},E=new Function("__bundle","__checkForLegacyModules","__mid","__amdValue","var define \x3d function(mid, factory){define.called \x3d 1; __amdValue.result \x3d factory || mid;},\t   require \x3d function(){define.called \x3d 1;};try{define.called \x3d 0;eval(__bundle);if(define.called\x3d\x3d1)return __amdValue;if((__checkForLegacyModules \x3d __checkForLegacyModules(__mid)))return __checkForLegacyModules;}catch(e){}try{return eval('('+__bundle+')');}catch(e){return e;}"),
z=function(d,b,h){var e=[];c.forEach(d,function(b){function d(a){a=E(a,f,b,A);a===A?e.push(n[c]=A.result):(a instanceof Error&&(console.error("failed to evaluate i18n bundle; url\x3d"+c,a),a={}),e.push(n[c]=/nls\/[^\/]+\/[^\/]+$/.test(c)?a:{root:a,_v1x:1}))}var c=h.toUrl(b+".js");if(n[c])e.push(n[c]);else{var g=h.syncLoadNls(b);g||(g=f(b.replace(/nls\/([^\/]*)\/([^\/]*)$/,"nls/$2/$1")));if(g)e.push(g);else if(a)a.get({url:c,sync:!0,load:d,error:function(){e.push(n[c]={})}});else try{h.getText(c,!0,
d)}catch(k){e.push(n[c]={})}}});b&&b.apply(null,e)},f=function(a){for(var b,d=a.split("/"),c=e.global[d[0]],h=1;c&&h<d.length-1;c=c[d[h++]]);c&&((b=c[d[h]])||(b=c[d[h].replace(/-/g,"_")]),b&&(n[a]=b));return b};p.getLocalization=function(a,d,c){var h;a=u(a,d,c);y(a,!b.isXdUrl(b.toUrl(a+".js"))?function(a,d){z(a,d,b)}:b,function(a){h=a});return h};return d.mixin(p,{dynamic:!0,normalize:function(a,d){return/^\./.test(a)?d(a):a},load:y,cache:n,getL10nName:x})})},"mw-browser-utils/detect/css":function(){define(["dojo/has"],
function(e){function b(b,d){var a=!1,c=b.charAt(0).toUpperCase()+b.slice(1),e=l.length,p=d.style;if("string"===typeof p[b])a=!0;else for(;e;)if(e-=1,"string"===typeof p[l[e]+c]){a=!0;break}return a}var l=["Webkit","Moz","O","ms","Khtml"],c=e.add;c("css-enabled",function(b,d,a){var c;b=d.documentElement;var e;if(!(e=d.body))c=!0,e=b.insertBefore(d.createElement("body"),b.firstChild);b=e;e=a.style.display;a.style.display="none";b.insertBefore(a,b.firstChild);d=0===a.offsetWidth;b.removeChild(a);a.style.display=
e;c&&b.parentNode.removeChild(b);return d});c("css-content-box",function(b,d,a){var c,g;b=d.documentElement;var l=null;if(e("css-enabled")){if(!(g=d.body))c=!0,g=b.insertBefore(d.createElement("body"),b.firstChild);a.style.cssText="position: absolute; top: -4000px; width: 40px; height: 40px; border: 1px solid black;";g.insertBefore(a,g.firstChild);l=40===a.clientWidth;g.removeChild(a);a.style.cssText=""}c&&g.parentNode.removeChild(g);return l});c("css-position-fixed",function(b,d,a){var c,g,l=d.documentElement,
F=null;if(e("css-enabled")){b=a.cloneNode(!1);if(!(g=d.body))c=!0,g=l.insertBefore(d.createElement("body"),l.firstChild);d=g.style.cssText;g.style.cssText="padding:0;margin:0";a.style.cssText="position:fixed;top:42px";g.insertBefore(b,g.firstChild);g.insertBefore(a,b);F=a.offsetTop!==b.offsetTop;g.removeChild(a);g.removeChild(b);g.style.cssText=d;a.style.cssText=""}c&&g.parentNode.removeChild(g);return F});c("css-rgba",function(b,d,a){b=/^rgba/;d=null;if(e("css-enabled"))try{a.style.color="rgba(1,1,1,0.5)",
d=b.test(a.style.color),a.style.color=""}catch(c){}return d});c("css-border-radius",function(c,d,a){return b("borderRadius",a)});c("css-box-shadow",function(c,d,a){return b("boxShadow",a)});c("css-box-sizing",function(c,d,a){return b("boxSizing",a)});c("css-opacity",function(c,d,a){return b("opacity",a)});c("css-opacity-filter",function(b,d){return!e("css-opacity")&&"undefined"!==typeof d.documentElement.filters});c("css-resize",function(c,d,a){return b("resize",a)});c("css-selectable",function(c,
d,a){return b("userSelect",a)});c("css-style-float",function(c,d,a){return b("styleFloat",a)});c("css-pointerevents",function(c,d,a){return b("pointerEvents",a)});c("css-text-overflow",function(c,d,a){return b("textOverflow",a)});c("css-text-shadow",function(c,d,a){return b("textShadow",a)});c("css-transform",function(c,d,a){return b("transform",a)});return e})},"mw-browser-utils/detect/object":function(){define(["dojo/has"],function(e){var b=e.add,l={}.toString,c=Object;b("object-create",function(){return"[object Function]"===
l.call(c.create)});b("object-getprototypeof",function(){return"[object Function]"===l.call(c.getPrototypeOf)});b("object-seal",function(){return"[object Function]"===l.call(c.seal)});b("object-freeze",function(){return"[object Function]"===l.call(c.freeze)});b("object-issealed",function(){return"[object Function]"===l.call(c.isSealed)});b("object-isfrozen",function(){return"[object Function]"===l.call(c.isFrozen)});b("object-keys",function(){return"[object Function]"===l.call(c.keys)});b("object-preventextensions",
function(){return"[object Function]"===l.call(c.preventExtensions)});b("object-isextensible",function(){return"[object Function]"===l.call(c.isExtensible)});b("object-defineproperty",function(){return"[object Function]"===l.call(c.defineProperty)});b("object-defineproperties",function(){return"[object Function]"===l.call(c.defineProperties)});b("object-getownpropertydescriptor",function(){return"[object Function]"===l.call(c.getOwnPropertyDescriptor)});b("object-getownpropertynames",function(){return"[object Function]"===
l.call(c.getOwnPropertyNames)});b("object-es5",function(){return e("object-create")&&e("object-defineproperties")&&e("object-defineproperty")&&e("object-freeze")&&e("object-getownpropertydescriptor")&&e("object-getownpropertynames")&&e("object-getprototypeof")&&e("object-isextensible")&&e("object-isfrozen")&&e("object-issealed")&&e("object-keys")&&e("object-preventextensions")&&e("object-seal")});return e})},"*now":function(e){e(['dojo/i18n!*preload*inspector/nls/browsercheck*["ar","ca","cs","da","de","el","en-gb","en-us","es-es","fi-fi","fr-fr","he-il","hu","it-it","ja-jp","ko-kr","nl-nl","nb","pl","pt-br","pt-pt","ru","sk","sl","sv","th","tr","zh-tw","zh-cn","ROOT"]'])}}});
define("inspector/browsercheck",[],1);
//# sourceMappingURL=browsercheck.js.map