function technologies = get_technologies(version)
%GET_TECHNOLOGIES Create table of technology names
%   TECHNOLOGIES = GET_TECHNOLOGIES(VERSION) returns an (n x 2) 
%   cell array of strings constituting a translation table for 
%   ICC-profile technologies.  The first column contains the
%   valid 4-byte profile signatures for the technologies, while
%   the second column contains the corresponding strings for 
%   the Technology tag in the profile structure, or for a
%   Technology tag embedded in a profileSequenceDescTag in
%   a DeviceLink profile structure.  VERSION is optional and is
%   the major-version number of the relevant ICC profile spec;
%   currently there is no dependence on VERSION, which defaults
%   to 2.
%
%   See ICCREAD, ICCWRITE.

%   Copyright 2005 The MathWorks, Inc.
%      Poe
%   Original authors: Scott Gregory, Toshia McCabe, Robert Poe 07/28/05

if nargin < 1
    version = 2;
end

% Build up a list of defined technologies:
technologies = {   ...
        'fscn', 'Film Scanner'; ...
        'dcam', 'Digital Camera'; ...
        'rscn', 'Reflective Scanner'; ...
        'ijet', 'Ink Jet Printer'; ...
        'twax', 'Thermal Wax Printer'; ...
        'epho', 'Electrophotographic Printer'; ...
        'esta', 'Electrostatic Printer'; ...
        'dsub', 'Dye Sublimation Printer'; ...
        'rpho', 'Photographic Paper Printer'; ...
        'fprn', 'Film Writer'; ...
        'vidm', 'Video Monitor'; ...
        'vidc', 'Video Camera'; ...
        'pjtv', 'Projection Television'; ...
        'CRT ', 'Cathode Ray Tube Display'; ...
        'PMD ', 'Passive Matrix Display'; ...
        'AMD ', 'Active Matrix Display'; ...
        'KPCD', 'Photo CD'; ...
        'imgs', 'PhotoImageSetter'; ...
        'grav', 'Gravure'; ...
        'offs', 'Offset Lithography'; ...
        'silk', 'Silkscreen'; ...
        'flex', 'Flexography'};

