classdef LineGroupedView < internal.matlab.inspector.InspectorProxyMixin

    properties
        Color,
        LineStyle,
        LineWidth,
        Marker,
        MarkerSize,
        MarkerEdgeColor,
        MarkerFaceColor,
        Clipping,
        AlignVertexCenters,
        XData,
        YData,
        ZData,
        UIContextMenu,
        BusyAction,
        BeingDeleted,
        Interruptible,
        CreateFcn,
        DeleteFcn,
        ButtonDownFcn,
        Type,
        Tag,
        UserData,
        Selected,
        SelectionHighlight,
        HitTest,
        PickableParts,
        DisplayName,
        Annotation,
        Children,
        Parent,
        Visible,
        HandleVisibility,
    end

    methods
        function this = LineGroupedView(obj)
            this@internal.matlab.inspector.InspectorProxyMixin(obj);

            g1 = this.createGroup('Line', 'MATLAB:codetools:inspector:LineProxyGroupName', ...
                'Line Group');
            g1.addProperties(...
                 'LineStyle', ...
                 'LineWidth', ...
                 'Color', ...
                 'AlignVertexCenters' ...
            );

            g2 = this.createGroup('Markers', 'Markers', ...
                'Markers Group');
            g2.addProperties(...
                 'Marker', ...
                 'MarkerSize', ...
                 'MarkerEdgeColor', ...
                 'MarkerFaceColor' ...
            );

            g3 = this.createGroup('Data', 'Data', ...
                'Data Group');
            g3.addProperties(...
                 'XData', ...
                 'YData', ...
                 'ZData', ...
                 'XDataSource', ...
                 'YDataSource', ...
                 'ZDataSource', ...
                 'XDataMode' ...
            );

            g4 = this.createGroup('Visibility', 'Visibility', ...
                'Visibility Group');
            g4.addProperties(...
                 'Visible', ...
                 'Clipping', ...
                 'EraseMode' ...
            );

            g5 = this.createGroup('Identifiers', 'Identifiers', ...
                'Identifiers Group');
            g5.addProperties(...
                 'Type', ...
                 'Tag', ...
                 'UserData', ...
                 'DisplayName', ...
                 'Annotation' ...
            );

            g6 = this.createGroup('HandleVisibility', 'Handle Visibility', ...
                'Handle Visibility Group');
            g6.addProperties(...
                 'Parent', ...
                 'Children', ...
                 'HandleVisibility' ...
            );

            g7 = this.createGroup('InteractiveControl', 'Interactive Control', ...
                'Interactive Control Group');
            g7.addProperties(...
                 'ButtonDownFcn', ...
                 'UIContextMenu', ...
                 'Selected', ...
                 'SelectionHighlight' ...
            );

            g8 = this.createGroup('CallbackExecutionControl', 'Callback Execution Control', ...
                'Callback Execution Control Group');
            g8.addProperties(...
                 'PickableParts', ...
                 'HitTest', ...
                 'Interruptible', ...
                 'BusyAction' ...
            );

            g9 = this.createGroup('CreationandDeletionControl', 'Creation and Deletion Control', ...
                'Creation and Deletion Control Group');
            g9.addProperties(...
                 'CreateFcn', ...
                 'DeleteFcn', ...
                 'BeingDeleted' ...
            );

        end
    end
end
